### ISSUE TITLE
Field "resource_ids" defined in some of the rule yaml files are not being used in the scanners

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1012]
for example, in big query rule we have
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/rules/bigquery_rules.yaml#L24-L27
and the field resource_ids is only used to check if it's defined but the value is not used
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/google/cloud/security/scanner/audit/bigquery_rules_engine.py#L127-L131

Bucket rule:
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/rules/bucket_rules.yaml#L22-L24
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/google/cloud/security/scanner/audit/buckets_rules_engine.py#L128-L133

CloudSQL rule:
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/rules/cloudsql_rules.yaml#L20-L23
https://github.com/GoogleCloudPlatform/forseti-security/blob/6294a564a15daf8b293dd983a15d541b468d8497/google/cloud/security/scanner/audit/cloudsql_rules_engine.py#L128-L133

**Comment by arbeit** [comment]
I would like to take a stab at this one unless someone else is working on it.

**Comment by mirons-google** [comment]
Hey @arbeit thanks, I think there's some discussion if this should be done in 1.X or in 2.0 versions. @blueandgold can help you make that decision.

**Comment by arbeit** [comment]
Thanks for the feedback. I happen to have a bit of time on my hands and would like to make a more substantial contribution. Maybe you can point me to another bug or feature request that I could take on?

**Comment by joecheuk** [comment]
Hey @ahoying @blueandgold , do you guys think we should at least hide/remove the unused fields in v1?

**Comment by blueandgold** [comment]
We do not have any existing changes or release plans for v1, as we are focusing on v2.  So, this change will be best done in v2, which will save us work to port it to v2, as well as encourage customers to migrate to v2.

**Comment by blueandgold** [comment]
This also includes the ```project``` and ```network``` fields from the instance_network_interface_rules.yaml are not used.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/rules/instance_network_interface_rules.yaml#L22-L23

**Comment by mtcmorris** [comment]
Any update on this? From what I can see specifically buckets the resource ids don't appear to be used for scoping like I'd expect (v2.3.0).  We have many projects in our org and in a few, public buckets are acceptable but in the rest they're not.  Attempting to write a "whitelist" style rule that allows for public buckets only within certain projects.

Happy to start work on a fix if that'd be accepted.

**Comment by joecheuk** [comment]
Hi @mtcmorris ,

We have updated the bigquery scanner to use the resource_id field but we don't yet have the bandwidth to tackle the bucket scanner. Would be awesome if you can contribute and I am more than happy to work with you to get the fix in Forseti!

Thanks,
Joe

**Comment by joecheuk** [comment]
The implementation will be very similar to this PR which addressed the same problem for bigquery scanner.

https://github.com/GoogleCloudPlatform/forseti-security/pull/1884

**Comment by jjawad-google** [comment]
We plan to fix this in scanner 2.0.
