### ISSUE TITLE
Switch from using the stackdriver agent to the python client

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1014]
- [Setting up logging](https://cloud.google.com/logging/docs/setup/python)
- [Installation](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-python)

**Comment by mirons-google** [comment]
**Issue Review**: Final implementation should include a check and/or a configuration option for this.

**Comment by blueandgold** [comment]
We shouldn't need this now, as we have properly configured fluentd in #1494, which is more portable between different platforms than using a python client.
