### ISSUE TITLE
Handle exception if the firewall json is not properly formatted.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#102]
Address the problem if the json file contains a single rule, either raise an exception early or properly format it as a single item list transparently.

**Comment by mirons-google** [comment]
@blueandgold can you provide an example of a problematic rule?

**Comment by carise** [comment]
This is because the enforcer is expecting a list of rules and bombs out when you pass it a json object.

**Comment by blueandgold** [comment]
Yup, if the firewall rules are not provided as a list, as in this example.
https://github.com/GoogleCloudPlatform/forseti-security/blob/master/google/cloud/security/enforcer/samples/default_allow_policy.json

So, if someone just have a single rule, they still need to put into a list.  i.e. they can not just have this.

```
    {
        "sourceRanges": ["0.0.0.0/0"],
        "description": "Allow ICMP from anywhere",
        "allowed": [
            {
                "IPProtocol": "icmp"
            }
        ],
        "name": "allow-icmp"
    }
```
