### ISSUE TITLE
Notifier attachment should be in CSV format rather than json.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1048]
This is to help with easier readability.

**Comment by jiyunyao** [comment]
Can you please elaborate a little on why CSV over JSON? @blueandgold

**Comment by blueandgold** [comment]
Current Forseti json attachment show up like this, which is hard to read.

![image](https://user-images.githubusercontent.com/6977544/37731357-1b99dc30-2cff-11e8-9fc5-2bccd11b4546.png)

Customers have preferred CSV attachment like this, which is easier to read.

![image](https://user-images.githubusercontent.com/6977544/37731303-faadac2c-2cfe-11e8-9e1f-11d7d9a3a076.png)

**Comment by jiyunyao** [comment]
My 2c: With JSON, you should be able to control the dump format so it looks better. With CSV, it doesn't support hierarchical data structure which might limit the potential use case in the future.

**Comment by blueandgold** [comment]
Yes, good point; we actually do plan to allow user to specify whether they
want json or csv.  This is the first step, since csv is the preferred
default and is a direct port of the existing scanner attachment's format.
And to make the file format configurable, will require some restructuring
of the notifier's configuration schema.

**Comment by blueandgold** [comment]
Just to track this more visibly, opened issue #1287.
