### ISSUE TITLE
2.0 - Developers should be able to build protos within installing using setup.py

### ISSUE THREAD

**Issue by ahoying** [GoogleCloudPlatform/forseti-security#1049]
When build_protos.py was moved into a library, the ability to just build the protos was lost. This functionality is needed for local development and testing. I recommend adding a new command to setup.py:

...

class BuildProtosCommand(install):
    """Post installation command."""

    def run(self):
        build_protos()

    cmdclass={
        'install': PostInstallCommand,
        'build_protos': BuildProtosCommand,
    },

**Comment by mirons-google** [comment]
Resolved in #1050
