### ISSUE TITLE
Unify the Notification Between Scanner and Notifier

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1060]
Currently, IAM, IAP, and Firewall scanners send out notifications and file exports of violations, along with Notifier.  This needs to be unified, so that customers will have the same experience.

**Comment by arbeit** [comment]
@blueandgold this is my understanding of what needs to be done:

# Summary
 * Various scanner implementations were copy / pasted / adjusted without refactoring the common code that e.g. emits the results
 * the `notifier` configuration section is gratuitously complex and repetitive (e.g. pipelines are defined for each particular scanner as opposed to the `notifier` in general)
 * some scanners have their own logic that emits `CVS` files or emails (e.g. `firewall_rules_scanner`) while others merely write the violations to the database (e.g. `cloudsql_rules_scanner` etc.)

# Proposal

 1. Pipelines should be defined only once (at the top level) in the `notifier` configuration.
 1. Violations (if notifications are enabled for the scanner in question) will be sent via all the pipelines configured.
 1. Resource-level pipeline specifications are invalid. Users may only define whether notifications are to be emitted for the resource / scanner in question.
 1. A single email / `CSV` file is to be sent / uploaded containing all violations found by the scanners for which notifications are enabled
 1. The `notifier::run()` method shall read these violations from the database and emit notifications as configured (how will the `notifier` run be triggered?)

**Comment by blueandgold** [comment]
Fixed by #1260
