### ISSUE TITLE
Quickstart instructions broken - "Invalid choice 'service-management'"

### ISSUE THREAD

**Issue by paultiplady** [GoogleCloudPlatform/forseti-security#1066]
- [x] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).

1.1.10 (also tested on v 1.1.9)

 - [x] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
setup_forseti.py
 - [x] Include errors, log output, and host operating system, including installed packages.
 - [x] Note how you deployed (via Deployment Manager, local system, etc.).

When following the quickstart instructions, deploying using Deployment Manager and Google Cloud Shell, I get the following error:

```
Enabling the IAM API...
ERROR: (gcloud.alpha) Invalid choice: 'service-management'.
Usage: gcloud alpha [optional flags] <group | command>
  group may be           app | auth | billing | compute | config | container |
                         dataflow | deployment-manager | emulators | endpoints |
                         firebase | functions | genomics | iot | ml |
                         ml-engine | organizations | projects | pubsub |
                         resource-manager | resources | scheduler | services |
                         source | spanner | tasks
  command may be         init | interactive | search-help
```

(This failure occurs for all of the APIs that the startup script is trying to  enable).

My `gcloud` has a `gcloud service-management` command, but not a `gcloud alpha service-management` one, being version :

```
Google Cloud SDK 188.0.1
alpha 2017.09.15
app-engine-go
app-engine-java 1.9.61
app-engine-php " "
app-engine-python 1.9.66
app-engine-python-extras 1.9.63
beta 2017.09.15
bq 2.0.28
cbt
cloud-datastore-emulator 1.4.0
core 2018.02.08
datalab 20180119
docker-credential-gcr
gcd-emulator v1beta3-1.0.0
gsutil 4.28
kubectl
pubsub-emulator 2018.02.02
```

**Comment by mirons-google** [comment]
Thanks for opening the issue @paultiplady! @joecheuk will follow-up shortly with our planned next steps to get this resolved for you (and others).

**Comment by joecheuk** [comment]
Hi @paultiplady , thank you for opening the issue! We have put in a hotfix to the master branch and everything should be working now. Can you do a `git pull` in your forseti-security folder to update the files and start the installation process again?

**Comment by paultiplady** [comment]
That has resolved the issue, thanks for the quick response!

**Comment by joecheuk** [comment]
Hi @paultiplady ,

No problem at all! I will just go ahead and close this issue for now, feel free to reach out if you have more questions!

Best regards,
Joe
