### ISSUE TITLE
Where to Run this command ?forseti_inventory --forseti_config path/to/forseti_conf.yaml  

### ISSUE THREAD

**Issue by aviakasurvivor** [GoogleCloudPlatform/forseti-security#1078]
Where to Run this command-:

**forseti_inventory --forseti_config path/to/forseti_conf.yaml** 

Upon successful installation, I am unable to understand where am I supposed to run this command,
In Google Cloud Shell when I come to the configs directory I can see the file forseti_conf.yaml.in and 2 other files which are stored in cloud Storage.
But When I try to run the command there I am receiving an error
**-bash: forseti_inventory: command not found**
When I am in the ssh shell of the VM created in my home/avi(my username) there is nothing inside it ; No Forseti-security folder.

I am unable to understand where I am supposed to run that command.
Please Help.

**Comment by joecheuk** [comment]
Hi @aviakasurvivor ,

Thanks for opening the issue! Forseti security is installed under user `ubuntu`, can you ssh to the VM and run command `sudo su ubuntu`, change the current directory to `/home/ubuntu` and you should be able to see the forseti-security folder there. Once you switched user to `ubuntu`, you should be able to execute all the forseti commands. The local configuration file is located at forseti-security/configs/forseti_conf.yaml, you can edit the file and run forseti commands by specifying this local configuration file.

Hope this helps, please let us know if are able to resolve the issue.

Best regards,
Joe

**Comment by joecheuk** [comment]
Hi @aviakasurvivor ,

I will go ahead and close this issue for now, feel free to reach out again if you have any questions!

Best regards,
Joe
