### ISSUE TITLE
Travis build passed even if some unit tests failed

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1083]
https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/340711717

----------------------------------------------------------------------
Ran 764 tests in 34.548s
FAILED (errors=2, skipped=3)
Running pylint.
Using config file /forseti-security/pylintrc
------------------------------------
Your code has been rated at 10.00/10
The command "./setup/scripts/run_docker_tests.sh" exited with 0.
after_success
......
Done. Your build exited with 0.

**Comment by mirons-google** [comment]
I presume this is because the last command `pylint` ended with success (exit code 0). I'll take a look at fixing this.

**Comment by mirons-google** [comment]
This is resolved in #1085
