### ISSUE TITLE
Handle SQLAlchemy Exceptions in the DAO When Schema Changes

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#109]
For instance in g/c/f/services/scanner/dao.py

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/scanner/dao.py#L138

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/scanner/dao.py#L154

**Comment by carise** [comment]
#228 must be done before thinking about how to handle db migrations.

**Comment by joecheuk** [comment]
Relates #1828

**Comment by mirons-google** [comment]
@joecheuk can this be closed?

**Comment by joecheuk** [comment]
@mirons-google Yes, this can be closed as we have ways to handle schema updates now.
