### ISSUE TITLE
FS 2.0: Watch deployment.log via gcloud ssh looking for successful install

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1090]
Today we exit the installer when the deployment command from gcloud returns. A new and final step should be to use `gcloud compute ssh --command` to watch the deployment log for a successful installation on the host VM and then end the installation.

`gcloud compute --project "project" ssh --zone "zone" "vm" --command "tail -q +1f /tmp/deployment.log | sed '/^Execution of startup script finished$/q0'"`

**Comment by joecheuk** [comment]
Fixed in #1082
