### ISSUE TITLE
FS 2.0: --type behavior on the installer

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1091]
Today we have two pieces to install (server|client). The installer should install both if no type is given. If type is specified then only install the requested one.

Install both client and server:
`python setup/installer.py` 

Install server only:
`python setup.py/installer.py --type server`

Install client only:
`python setup.py/installer.py --type client`

**Comment by joecheuk** [comment]
Fixed in #1082
