### ISSUE TITLE
Hard-coded strings in FS2.0

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1105]
On a fresh installation of FS2.0 it seems we've hard-coded a path to the configuration file.

`[forseti-security] INFO __main__(read_env): reading environment variable FORSETI_SERVER_CONFIG = /home/jiyunyao/.forseti" `

**Comment by mirons-google** [comment]
Additionally, I see these appearing to be @jiyunyao related too.

`A  [forseti-security] INFO google.cloud.forseti.services.dao(create): Creating a new model entry in the database, name = testjy10 
A  [forseti-security] INFO google.cloud.forseti.services.model.modeller(create_model): Creating model: testjy10, inventory_id = 2018-02-15T22:00:07.40914 `

**Comment by jiyunyao** [comment]
That was me again logging in the VM to debug stuff~
