### ISSUE TITLE
FS 2.0 Data Integrity Errors

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1106]
In the VM instance logs of a fresh 2.0 installation I see stack traces regarding integrety checking errors on inserts.

``
"Feb 15 23:43:28 forseti-server[11906]: IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'iam_policy/testpolicy-test' for key 'PRIMARY'") [SQL: u'INSERT INTO `1122243423423422_resources` (full_name, type_name, name, type, policy_update_counter, display_name, email, data, parent_type_name) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (('organization/12345/iam_policy/12345/', 'iam_policy/12345', '12345', 'iam_policy', 0, '', '', '{"bindings": [{"role": "organizations/12345/roles/PersonFolderRole", "members": ["user:user@domain.com"]}, {"role": "organizations/12345 ... (16878 characters truncated) ... ``

If you need the full error log let me know.

**Comment by joecheuk** [comment]
Fixed in PR #1102
