### ISSUE TITLE
FS2.0 Stops mysteriously stops running

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1108]
FS 2.0 runs for a period of time and then this series of log entries happen across both client and server (start reading from the bottom). This is best viewed if you copy the log messages below into a viewer that doesn't wrap the log lines.

``
A  Feb 16 16:00:01 forseti-security-server-12345-vm CRON[26867]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 16:00:01 forseti-security-server-12345-vm CRON[26868]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 15:17:01 forseti-security-client-54321-vm CRON[23232]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 15:17:01 forseti-security-server-12345-vm CRON[26601]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 14:17:01 forseti-security-server-12345-vm CRON[26220]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 14:17:01 forseti-security-client-54321-vm CRON[22861]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 14:00:02 forseti-security-server-12345-vm CRON[26087]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 14:00:01 forseti-security-server-12345-vm CRON[26088]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 13:17:01 forseti-security-server-12345-vm CRON[25816]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 13:17:01 forseti-security-client-54321-vm CRON[22505]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 12:17:01 forseti-security-client-54321-vm CRON[22149]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 12:17:01 forseti-security-server-12345-vm CRON[25409]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 12:00:02 forseti-security-server-12345-vm CRON[25275]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 12:00:01 forseti-security-server-12345-vm CRON[25276]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 11:17:01 forseti-security-server-12345-vm CRON[25011]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 11:17:01 forseti-security-client-54321-vm CRON[21759]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 10:18:12 forseti-security-server-12345-vm cloud_sql_proxy[11884]: 2018/02/16 10:18:12 Instance fs-20-install-2:us-central1:forseti-security-12345 closed connection 
A  Feb 16 10:17:01 forseti-security-server-12345-vm CRON[24645]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 10:17:01 forseti-security-client-54321-vm CRON[21384]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 10:00:01 forseti-security-server-12345-vm CRON[24518]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 10:00:01 forseti-security-server-12345-vm CRON[24519]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 09:17:01 forseti-security-server-12345-vm CRON[24251]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 09:17:01 forseti-security-client-54321-vm CRON[21009]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 08:17:01 forseti-security-server-12345-vm CRON[23894]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 08:17:01 forseti-security-client-54321-vm CRON[20622]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 08:00:02 forseti-security-server-12345-vm CRON[23767]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 08:00:01 forseti-security-server-12345-vm CRON[23768]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 07:17:01 forseti-security-server-12345-vm CRON[23510]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 07:17:01 forseti-security-client-54321-vm CRON[20234]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 07:02:17 forseti-security-server-12345-vm systemd[1]: Started Daily apt download activities. 
A  Feb 16 07:02:10 forseti-security-server-12345-vm systemd[1]: Starting Daily apt download activities... 
A  Feb 16 06:33:56 forseti-security-client-54321-vm systemd[1]: Started Daily apt upgrade and clean activities. 
A  Feb 16 06:33:53 forseti-security-client-54321-vm systemd[1]: Starting Daily apt upgrade and clean activities... 
A  Feb 16 06:30:18 forseti-security-server-12345-vm systemd[1]: Started Daily apt upgrade and clean activities. 
A  Feb 16 06:30:15 forseti-security-server-12345-vm systemd[1]: Starting Daily apt upgrade and clean activities... 
A  Feb 16 06:25:01 forseti-security-server-12345-vm CRON[22624]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )) 
A  Feb 16 06:25:01 forseti-security-client-54321-vm CRON[19497]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )) 
A  Feb 16 06:17:01 forseti-security-server-12345-vm CRON[22573]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 06:17:01 forseti-security-client-54321-vm CRON[19447]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 06:00:02 forseti-security-server-12345-vm CRON[22448]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 06:00:01 forseti-security-server-12345-vm CRON[22449]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 05:17:01 forseti-security-client-54321-vm CRON[19082]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 05:17:01 forseti-security-server-12345-vm CRON[22191]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 05:10:40 forseti-security-server-12345-vm dhclient[887]: bound to 10.128.0.2 -- renewal in 39073 seconds. 
A  Feb 16 05:10:40 forseti-security-server-12345-vm systemd[1]: Started System Logging Service. 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd: rsyslogd's userid changed to 104 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd: rsyslogd's groupid changed to 108 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd-2222: command 'KLogPermitNonKernelFacility' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.16.0 try http://www.rsyslog.com/e/2222 ] 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd-2007: action 'action 11' suspended, next retry is Fri Feb 16 05:11:10 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ] 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd-2039: Could not open output pipe '/dev/xconsole':: No such file or directory [v8.16.0 try http://www.rsyslog.com/e/2039 ] 
A  Feb 16 05:10:40 forseti-security-server-12345-vm systemd[1]: Starting System Logging Service... 
A  Feb 16 05:10:40 forseti-security-server-12345-vm systemd[1]: Stopped System Logging Service. 
A  Feb 16 05:10:40 forseti-security-server-12345-vm systemd[1]: Stopping System Logging Service... 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="22136" x-info="http://www.rsyslog.com"] start 
A  Feb 16 05:10:40 forseti-security-server-12345-vm rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="832" x-info="http://www.rsyslog.com"] exiting on signal 15. 
A  Feb 16 05:10:40 forseti-security-server-12345-vm dhclient[887]: DHCPACK of 10.128.0.2 from 169.254.169.254 
A  Feb 16 05:10:40 forseti-security-server-12345-vm dhclient[887]: DHCPREQUEST of 10.128.0.2 on ens4 to 169.254.169.254 port 67 (xid=0x2028d337) 
A  Feb 16 04:37:37 forseti-security-client-54321-vm dhclient[929]: bound to 10.128.0.3 -- renewal in 42593 seconds. 
A  Feb 16 04:37:37 forseti-security-client-54321-vm systemd[1]: Started System Logging Service. 
A  Feb 16 04:37:37 forseti-security-client-54321-vm systemd[1]: Starting System Logging Service... 
A  Feb 16 04:37:37 forseti-security-client-54321-vm systemd[1]: Stopped System Logging Service. 
A  Feb 16 04:37:37 forseti-security-client-54321-vm systemd[1]: Stopping System Logging Service... 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd-2007: action 'action 11' suspended, next retry is Fri Feb 16 04:38:07 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ] 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd: rsyslogd's userid changed to 104 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd: rsyslogd's groupid changed to 108 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd-2222: command 'KLogPermitNonKernelFacility' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.16.0 try http://www.rsyslog.com/e/2222 ] 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd-2039: Could not open output pipe '/dev/xconsole':: No such file or directory [v8.16.0 try http://www.rsyslog.com/e/2039 ] 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="18822" x-info="http://www.rsyslog.com"] start 
A  Feb 16 04:37:37 forseti-security-client-54321-vm rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="874" x-info="http://www.rsyslog.com"] exiting on signal 15. 
A  Feb 16 04:37:37 forseti-security-client-54321-vm dhclient[929]: DHCPACK of 10.128.0.3 from 169.254.169.254 
A  Feb 16 04:37:37 forseti-security-client-54321-vm dhclient[929]: DHCPREQUEST of 10.128.0.3 on ens4 to 169.254.169.254 port 67 (xid=0x7c9c5dfe) 
A  Feb 16 04:17:01 forseti-security-client-54321-vm CRON[18670]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 04:17:01 forseti-security-server-12345-vm CRON[21796]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 04:00:01 forseti-security-server-12345-vm CRON[21667]: (CRON) info (No MTA installed, discarding output) 
A  Feb 16 04:00:01 forseti-security-server-12345-vm CRON[21668]: (ubuntu) CMD (/home/ubuntu/forseti-security/setup/gcp/scripts/run_forseti.sh) 
A  Feb 16 03:17:01 forseti-security-client-54321-vm CRON[18302]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 03:17:01 forseti-security-server-12345-vm CRON[21413]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[1]: Removed slice User Slice of jiyunyao. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[1]: Stopped User Manager for UID 1002. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Received SIGRTMIN+24 from PID 21069 (kill). 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Stopped target Timers. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Stopped target Sockets. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Stopped target Paths. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Stopped target Basic System. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Stopped target Default. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Starting Exit the Session... 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[17792]: Reached target Shutdown. 
A  Feb 16 02:18:22 forseti-security-server-12345-vm systemd[1]: Stopping User Manager for UID 1002... 
A  [forseti-security] INFO google.cloud.forseti.services.notifier.service(create_and_register_service): service <google.cloud.forseti.services.notifier.service.GrpcNotifier object at 0x7fbd243e27d0> created and registered``

**Comment by jiyunyao** [comment]
That was me logging in the VM to debug stuff~
