### ISSUE TITLE
Do not run forseti on server startup if the scanner rules are not configured.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1143]
Currently, `run_forseti.sh` is invoked on VM startup.  This happens even before rule files are properly configured and creating bad violations in the database.  So, until we are able to pre-configure the rule files as part of the installation, we should remove invoking `run_forseti.sh` on server startup.

Less importantly, this will also affect the initial inventory as gsuite setup will not be done yet by the user.

**Comment by joecheuk** [comment]
Resolved: #1155
