### ISSUE TITLE
Clean-up Model Tables after each Forseti Cron Run

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1144]
IIRC, the data model tables need to be clean-up, even if there are violations from it.  So, this means that the `run_forseti.sh` need to do this clean-up.

If I don't recall this correctly, i.e the data models need to be retained because of violations, then we need to develop a way to clean them up later.

**Comment by joecheuk** [comment]
Resolved: #1146

Thanks @jiyunyao for helping out on this issue!
