### ISSUE TITLE
error: [Errno 90] Message too long

### ISSUE THREAD

**Issue by arbeit** [GoogleCloudPlatform/forseti-security#1161]
This error occurs when I run a `model create` command e.g.

    forseti --endpoint '[::]:50051' model create --id 2018-02-27T09:25:52.31687 inventory m3

I see in the server terminal window the following traceback

    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/handlers.py", line 864, in emit
        self.socket.sendto(msg, self.address)
    error: [Errno 90] Message too long
    Logged from file iam.py, line 291

This applies to the `2.0-dev` branch `commit 69b85715e2fe309994017cc10343edce3fda019b`

**Comment by joecheuk** [comment]
Limited the log message to 1024 characters in #1204  

We should have a better fix for this when we integrate stackriver logging APIs in #1202
