### ISSUE TITLE
Stackdriver log line "Writing violations to csv..." is not very descriptive

### ISSUE THREAD

**Issue by MartenvanWezel** [GoogleCloudPlatform/forseti-security#1179]
This line:

https://github.com/GoogleCloudPlatform/forseti-security/blob/3050f07ae3e0b51e2fc54cc3f0dd2ffb6dc9212f/google/cloud/security/scanner/scanner.py#L202

is a little weak - it would be very helpful to actually add the cloud storage URL so you can click through directly. If that isn't available at that point, perhaps move it to eg here:

https://github.com/GoogleCloudPlatform/forseti-security/blob/3050f07ae3e0b51e2fc54cc3f0dd2ffb6dc9212f/google/cloud/security/scanner/scanner.py#L255

**Comment by joecheuk** [comment]
Scanners shouldn't be sending out emails any more, resolving #1060 will also resolve this issue.

**Comment by joecheuk** [comment]
Notifier is now handling all the notifications (including writing to CSV) so this issue is no longer relevant.
