### ISSUE TITLE
We must standardize on a name for GCP resources that also binds them together with a common identifier

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1188]
This should include:
- service account names
- vm instance names
- gcs bucket names
- cloudsql instance names
- deployment template names

**Comment by joecheuk** [comment]
For now everything has been standardized, only minor issue left is the name of the vm instance contains suffix '-vm', this can be improved by removing the suffix in the future. 

We are using the last 4 digits of the timestamp  as the unique identifier.  For example, if the last 4 digits of the timestamp is 1234 then we have the followings:

service account names: forseti-client-gcp-1234, forseti-server-gcp-1234, forseti-server-gsuite-1234
vm instance names: forseti-server-1234-vm, forseti-client-1234-vm
gcs bucket names: forseti-server-1234, forseti-client-1234
cloudsql instance names: forseti-server-1234
deployment template names: forseti-server-1234, forseti-client-1234

**Comment by mirons-google** [comment]
@joecheuk thanks for making this happen. I think this is great with one minor nit: `forseti-server-vm-1234` instead of `forseti-server-1234-vm`. That way all names end in the same four digits.

**Comment by joecheuk** [comment]
Resolved #1201
