### ISSUE TITLE
Investigate why Travis didn't catch a bad import on a missing python module.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1192]
There was a bad import of a deleted file, but it was [found via code review](https://github.com/GoogleCloudPlatform/forseti-security/pull/1190/files), several days after the file was deleted.  

This is something Travis should've caught (i.e. build error) but did not, as every PR in between has been green.  So, it's worth looking into why Travis did not catch this.

**Comment by jjawad-google** [comment]
Transient issue. Will reopen if issue resurfaces.
