### ISSUE TITLE
Explain iamql Branches Clean-Up

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1203]
As discussed, we are not sure what all these iamql branches are for, so it would be nice to consolidate them.

iamql
https://github.com/GoogleCloudPlatform/forseti-security/tree/iamql

iamql-refactored
https://github.com/GoogleCloudPlatform/forseti-security/tree/iamql-refactored

iamql-rc1
https://github.com/GoogleCloudPlatform/forseti-security/tree/iamql-rc1

**Comment by blueandgold** [comment]
Per Jiyun, all 3 branches are still needed (different versions that they are trying out).  Will clean-up in future.

**Comment by mirons-google** [comment]
@jiyunyao can you confirm the above mentioned branches are still needed?

**Comment by jiyunyao** [comment]
Please feel free to delete them.

**Comment by blueandgold** [comment]
All deleted.
