### ISSUE TITLE
Screenshots or sample output?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/forseti-security#123]
Would be cool to have some screenshots or sample outputs (e.g. CSVs) without installing and seeing what it provides. My 2c.

**Comment by carise** [comment]
Hi ahmetb! Thanks for the input! We do have some test data, but nothing really formal... But definitely agree that some sample output would be helpful.

**Comment by blueandgold** [comment]
@mirons-google Would you like to do this as part of your documentation improvement effort?

**Comment by mirons-google** [comment]
I'm going to move this out of M1 as we've been focusing on inventory and scanning improvements in M1. In M2 (or when) we work on improving our outputs (emails, reports, etc.) we can revisit this.

**Comment by carise** [comment]
[Enabling GSuite Google Groups Collection](http://forsetisecurity.org/docs/howto/configure/gsuite-group-collection) would benefit from screenshots.

We could also create a sample csv of scanner violation output.

**Comment by blueandgold** [comment]
Bumping to P0 since it might be part of doc improvement for deployment.

**Comment by Tabrarian** [comment]
Apologies, I forgot to update here - I believe this is resolved; we've added sample output for scanner violations and images for GSuite Google Groups collection.
