### ISSUE TITLE
Please check this compound condition.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1239]
Based the exception message, is the use of `and` correct in the if condition?  Looks like it should be using `or`?

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/gcp_type/firewall_rule.py#L352-L357

```
        if self.direction == 'INGRESS':
            if (not self._source_ranges and not self._source_tags and not
                    self.source_service_accounts):
                raise InvalidFirewallRuleError(
                    'Ingress rule missing required field oneof "sourceRanges" '
                    'or "sourceTags" or "sourceServiceAccounts": "%s".' % self)
```

**Comment by ahoying** [comment]
Yes, that's correct. It see that none of them are defined and raises an exception that one of them most be defined. (More than one is okay).
