### ISSUE TITLE
Forseti should support HTTP

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1242]
This will allow customers to integrate Forseti into their application easily.

**Comment by blueandgold** [comment]
Look into cloud endpoints, which might be related to authN/authZ; related to that whole set of work.

**Comment by blueandgold** [comment]
After discussing internally, gRPC can support transcoding of http post requests, which can be mapped to gRPC's request method.
https://cloud.google.com/endpoints/docs/grpc/transcoding
