### ISSUE TITLE
Inventory should inventory groups and group members

### ISSUE THREAD

**Issue by xsgbloom** [GoogleCloudPlatform/forseti-security#126]
Google's current best practice is to leverage G Suite Groups for all role assignments within a project, in order to allow project access to be automated via Google Cloud Directory Sync.

It would be ideal if Forseti had the ability to scan within G Suite Groups that are assigned roles in projects in order to ensure that all members that exist in the Group meet the configured policies. G Suite Group membership information is available in the G Suite Admin SDK Directory API.

Please note that some organizations might use Google Groups (e.g. @googlegroups.com) however these groups are _not_ accessible via an API.

Some challenges this will pose:
- Identifying whether an address configured in a project's IAM console is a G Suite Group
- Identifying which G Suite domain the Group belongs to
- Gaining authorization to the G Suite domain's Directory API (via an OAuth scope grant)
- Handling nested Groups (e.g. Group members will also have to be identified as either a direct user or another group)

**Comment by blueandgold** [comment]
This issue is also tracked in #62 .  Will link both for now, as there are a lot of good details here.

**Comment by mirons-google** [comment]
In investigating this a bit here are some initial thoughts.
- The API to enable is the Admin SDK (not to be confused with the Directory API)

There are two possible approaches, my preferred one is the first

1) Inventory should call the admin api and get a list of all google groups and store that as part of it's inventory run
1a) Scanner should cross-check IAM policies for email addresses that are in the list of known groups
1b) When there's a match call the Admin SDK to expand the group and get it's members
1c) For any members that are of the type "[group](https://developers.google.com/admin-sdk/directory/v1/reference/members#resource)" repeat 1b
1d) Once a list of real users is built perform the reconciliation of the rule and reality

OR

2) Request all group members
2a) Call the admin sdk [users api](https://developers.google.com/admin-sdk/directory/v1/reference/users/get) for every member and note the HTTP response
2b) For requests that don't return a valid user response (to be tested) we assume it's a group
2c) For suspected accounts we call the group member api to see if it's a group and examine it's membership
2d) Repeat 2c until we have no more groups as members of the original group
2e) Perform reconciliation between rule and all user members.

**Comment by mirons-google** [comment]
**A work update**

_Completed_
- An initial schema submitted #159 
- Initial support using the Admin SDK is working on local installations #165 

_Todo_
- Update documentation (dependent on the item below)
- Add support for oauth using local keys on the gce instance with DWD

As it relates the to the latter we have a few options and I'd like to source some opinions on a preferred approach.

1) Create, request, and store the service account key on the gce instance
2) Create the key manually, store it in the meta-data server, have the application retrieve it
3) Create the key manually, have the user copy the key to the gce instance (or some variation there-of)
4) Create the key manually/programmatically and put it into Google key storage

@ahoying I know you might have some thoughts here on a preferred approach

**Comment by mirons-google** [comment]
PR #188 adds support for doing this on GCP installations.

Remaining work effort:
- Fetching and storing members of all groups

**Comment by mirons-google** [comment]
**A work update**

_Completed_

- An initial schema submitted #159 
- Initial support using the Admin SDK is working on local installations #165 
- Update for GCP installations #188 
- Creation of the group_members pipeline #196 

This resolves all remaining work necessary for inventory to inventory GSuite Google Groups. Marking as fixed.
