### ISSUE TITLE
Service Account ID is non-obvious in gsuite groups collection setup

### ISSUE THREAD

**Issue by MartenvanWezel** [GoogleCloudPlatform/forseti-security#1267]
https://forsetisecurity.org/docs/howto/configure/gsuite-group-collection.html

In the 'Create a service account' section, it says:
"Note: If you used the setup wizard to setup Forseti, it already creates a G Suite service account. You can go directly to the [next section.](https://forsetisecurity.org/docs/howto/configure/gsuite-group-collection.html#enable-the-service-account-in-your-g-suite-admin-control-panel)"

Next Section jumps past enabling domain-wide delegation though, so I think that's wrong. DwD still needs to be set up - at least in my setup there is a service account "forseti-server-gsuite-0830" and " forseti-server-gcp-0830" but neither has DwD

(Also, in that next section it asks for a "Client ID you copied above." - which I didn't do because I skipped it.)

**Comment by blueandgold** [comment]
This is a documentation update, and should also be addressed in the current 1.0 page.

**Comment by mirons-google** [comment]
Resolved in #1516
