### ISSUE TITLE
Need A More Deterministic Way to Know When A Model Is Ready for Use

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1283]
Currently, this is being handle by waiting for 10 seconds in `run_forseti.sh` script.  Which will break if the model creation takes longer (as happened before the POM demo).

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/setup/gcp/scripts/run_forseti.sh#L49-L51

So, we need a more deterministic way to know when a model is ready for use, rather than relying on waiting for 10 seconds, 20 seconds, 30 seconds, etc.

**Comment by blueandgold** [comment]
Relates to #1296

**Comment by joecheuk** [comment]
Resolved #1289
