### ISSUE TITLE
IAP Violations are not saved to GCS

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1316]
After installing RC2, did a `forseti notifier run` on the client VM, the notifier reports a problem and no violation is found on GCS.

![image](https://user-images.githubusercontent.com/6977544/37991056-f7cedb58-31bc-11e8-8037-66f37ee7bc14.png)

**Comment by blueandgold** [comment]
relates to issue #1315 , to get actual useful error messages for debugging

**Comment by blueandgold** [comment]
Just running the cloudsql notification will work fine, both email and gcs bucket.

**Comment by blueandgold** [comment]
Narrowed this down to the IAP notification.

**Comment by arbeit** [comment]
Want me to look at this?

**Comment by blueandgold** [comment]
Yes, please!

**Comment by arbeit** [comment]
Testing against

    commit aa3f63e0023cddf006cd3818d3f865ee5c16b471
    Merge: 39030cd0 db09dfbc
    Author: joecheuk <joecheuk@google.com>
    Date:   Tue Mar 27 20:16:41 2018

        Merge branch '2.0-rc2' into 2.0-dev

IAP email notifications work

![image](https://user-images.githubusercontent.com/1688051/38192067-7ef71bd8-366b-11e8-88cb-b79973d593c3.png)

**Comment by arbeit** [comment]
server says

    server_message: "Retrieved 50 violations for resource \'policy_violations\'"
    server_message: "Retrieved 1 violations for resource \'iap_violations\'"
    server_message: "Retrieved 1 violations for resource \'instance_network_interface_violations\'"
    server_message: "Retrieved 1 violations for resource \'forwarding_rule_violations\'"
    server_message: "Running \'email_violations\' notifier for resource \'iap_violations\'"
    server_message: "Running \'gcs_violations\' notifier for resource \'iap_violations\'"
    server_message: "Notification completed!"

However, I do not see the GCS upload. Looking into that now.

**Comment by arbeit** [comment]
Oops, `gsutil ls` sorting order threw me off :-P

The `GCS` upload **was** actually performed as well. IOW, cannot reproduce this issue on my end.

    (fsec) forseti-security $ gsutil ls -l gs://forset-violations/scanner_violations/ | head -n3
          1226  2018-04-02T09:41:55Z  gs://forset-violations/scanner_violations/violations.iap_violations.2018-03-24T00:49:02.891287.20180402T094154Z.csv
          1226  2018-04-02T09:55:18Z  gs://forset-violations/scanner_violations/violations.iap_violations.2018-03-24T00:49:02.891287.20180402T095517Z.csv
         65084  2018-03-20T21:23:08Z  gs://forset-violations/scanner_violations/violations.policy_violations.2018-03-14T14:49:36.101287.20180320T212307Z.json
