### ISSUE TITLE
Better error handling when server can not parse config file.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1340]
When there is problem to parse the config file, the client just gets an "connect" error as below.

![image](https://user-images.githubusercontent.com/6977544/38219691-a92c022c-368b-11e8-9f13-1d7b9b3414fd.png)

The message should be better formated, but also better handled so that the client can get a more helpful message.

**Comment by blueandgold** [comment]
Related to #1202 and multi-line logging using fluentd

**Comment by jjawad-google** [comment]
Stack traces were added for each error handling routine.
