### ISSUE TITLE
IAM Policy Violations in JSON is different from the CSV

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1343]
@arbeit , I'll send the files offline to you.  But the json file is 423.8KB, while the csv file is only 1.65KB.

**Comment by arbeit** [comment]
Hmmm .. it might be this particular line of code [`forseti/common/data_access/csv_writer.py#L499`](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/data_access/csv_writer.py#L499)

Investigating further..

**Comment by arbeit** [comment]
Apparently, [`forseti/common/data_access/csv_writer.py#L499`](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/data_access/csv_writer.py#L499) is a red herring. `inventory_data` is only [set by the firewall rules engine](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/scanner/audit/firewall_rules_engine.py#L589) but even that is stored in the `resource_data` column.

**Comment by arbeit** [comment]
I cannot reproduce this .. both the CSV and the json notifier use the same data, IOW it should make no difference how you serialize.

**Comment by arbeit** [comment]
Assumptions:

 1. the CSV format should be the one that is consumed by humans
 1. JSON is mostly for machines and more data is better

Decision: leave things as they are
