### ISSUE TITLE
write_csv: popping 'inventory_data' is superfluous and misleading 

### ISSUE THREAD

**Issue by arbeit** [GoogleCloudPlatform/forseti-security#1346]
The 3 lines of code [starting here](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/data_access/csv_writer.py#L497) should be removed.

First: the violations dictionary does not have an `inventory_data` key. Moreover, what data is dumped to `CSV` is actually governed by the ["field names"](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/data_access/csv_writer.py#L492) that are passed to the `csv.DictWriter` instance (see e.g. the policy violation field names [here](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/common/data_access/csv_writer.py#L370)) 

Also, see issue #1343 for more context.

**Comment by jjawad-google** [comment]
Everything appears to be working with no indication of breakage. Please feel free to reopen this issue if it resurfaces again.
