### ISSUE TITLE
Unable to find assigned role for gsuite service account

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1372]
The installer shows that it assigned `roles/iam.serviceAccountKeyAdmin` to the gsuite service account.  But I don't find this in the cloud console UI.

![image](https://user-images.githubusercontent.com/6977544/38346285-e3636aa2-3848-11e8-9fed-264a06f87138.png)

**Comment by joecheuk** [comment]
The installer is assigning the iam.serviceAccountKeyAdmin role on the gsuite service account to the gcp service account.The role is used to create and manage (and rotate) service account keys. It's not assigning anything to the gsuite account.

**Comment by mirons-google** [comment]
Suggestion: Make this a FAQ item.

**Comment by blueandgold** [comment]
I found where @ahoying is saying about where to see this now.  Have to click on the `Permissions` button in the UI.

![image](https://user-images.githubusercontent.com/6977544/39720852-71509ea8-51f2-11e8-9b1c-65330a742ce1.png)
