### ISSUE TITLE
Restrict permissions of the forseti-security directory on the server Linux VM

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1378]
Code on server VM should not be world executable in general.  Some directories `rules` or `configs` should not be world readable.  Double-check with @ahoying on this.

![image](https://user-images.githubusercontent.com/6977544/38347884-0f534ac4-3853-11e8-8728-264deded47ca.png)

**Comment by jjawad-google** [comment]
@ahoying could you take a look ?

**Comment by ahoying** [comment]
Current directory permissions are fine given the server VM is not an interactive VM where multiple users are expected to log in. All users who log into the server VM are expected to be admins with root privileges.
