### ISSUE TITLE
Configure Notifier to support inventory summary data

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1385]
In v1, we send out an inventory summary email after every inventory run and we don't have that feature any more in v2.

We should also allow:
1. Save inventory summary to GCS
2. Send the summary as an email
3. Switch between formats (e.g. json and csv)

**Comment by arbeit** [comment]
@antoine-castex I am looking into this issue. Can you please let me know
 1. what summary data is of interest?
 1. how you would like to use it?
 1.  what would be the best way to access/consume it?

**Comment by arbeit** [comment]
according to @antoine-castex an inventory summary file (in CSV or json format) that is uploaded to a configurable GCS path will do the job. [This is an example](https://pastebin.com/zqJ95vHd) (produced by testing PR #1416).

**Comment by antoine-castex** [comment]
This is exactly what we need

**Comment by arbeit** [comment]
The same inventory summary [in json format](https://pastebin.com/T4CFJjCm).
