### ISSUE TITLE
Mitigate Restarting the Server for Reading Updated Config File

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1396]
Currently, the server needs to be restarted in order to read any changes in an updated `forseti_conf.yaml` file.  This would effectively kill another running processes.  Such as if the user is doing something and the cron job runs.

So, it would be nice if the server does not have to be restarted, i.e. the server will read in the conf file when it does an operation.

**Comment by ahoying** [comment]
Reloading the configuration file live is very dangerous. If someone is editing the file on the system (even though we expect people to edit and push to GCS, this is not always going to be the case) then the editor may save the file in an intermediate state that is not valid, while they are editing. This will immediately cause the system to crash if it attempts to reload the configuration.

That is why most Linux daemons require a signal from the user to restart, either a SIGHUP, or running a command to force the reload.

I recommend that the system supports sighup and we add a grpc method so the cli can force a reload as well.

Normal operation should be something like:

1. Download a new configuration from GCS.
2. Validate the configuration.
3. If validation passes, send HUP to the service to reload.
