### ISSUE TITLE
Allow user to run the notifier on a specific scanner_index_id

### ISSUE THREAD

**Issue by arbeit** [GoogleCloudPlatform/forseti-security#1405]
We should support the use case of running the notifier directly on a given `scanner_index` e.g.

    forseti notifier run --scanner_index_id <scanner index id>

**Comment by blueandgold** [comment]
This is already fixed.
https://github.com/GoogleCloudPlatform/forseti-security/commit/fb9f868e1e42dce1c3644aaf089e5222912d75b3#diff-d2c4352d49590345d368eab7dad8a8c7
