### ISSUE TITLE
Addition of Forseti Under a Folder 

### ISSUE THREAD

**Issue by aviakasurvivor** [GoogleCloudPlatform/forseti-security#1417]
Hi Forseti Team,

Can I add the project under a folder in the organization and continue using it as my ORG Admin do not want to give Org Admin Role to a User?

**Comment by blueandgold** [comment]
Follow-up here with user to clarify that ORG admin is still needed to install, but the project can be located anywhere.

**Comment by joecheuk** [comment]
Hi @aviakasurvivor , 

You can create a Forseti project under a folder in the organization.

Please note that we are not assigning the Org Admin role to any of the Forseti service accounts. The only requirement is that the person who runs the installation will need to have the Org Admin role. Does that address your concern?

Thanks,
Joe

**Comment by joecheuk** [comment]
Hi @aviakasurvivor , I will close this issue for now - feel free to re open this issue if you still have more questions!
