### ISSUE TITLE
IAM & Bucket ACL Issues

### ISSUE THREAD

**Issue by ink0gnitas** [GoogleCloudPlatform/forseti-security#1428]
When I create a public bucket with "allUsers Storage Object Viewer" permission I get IAM violation "Allow only service accounts to have access" and no bucket ACL violation for the public buckets. 

Different scenario if I use "allUsers Storage Legacy Bucket Reader" where I get as expected bucket ACL violation if bucket. Is it by design like this?

How do I then whitelist public buckets using "allUsers Storage Object Viewer"?

Forseti: 2.0-rc2

**Comment by blueandgold** [comment]
Hi Karolis, the legacy bucket ACLs are managed by a separate scanner and rule file, specifically. [bucket_rules.yaml](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/rules/bucket_rules.yaml).

This is separate from IAM policy scanner, which uses the [iam_rules.yaml](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/rules/iam_rules.yaml) file.

The bucket ACL scanner only works in blacklist mode.  So, if you want to whitelist `allUsers`, simply just remove or comment out the `allUsers` block in the `bucket_rules.yaml`.

Please let us know if you have any other questions.
