### ISSUE TITLE
run_forseti.sh should detect previously launched jobs and act accordingly

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1436]
`run_forseti.sh` is the command executed via cron. This command should detect that existing invocations of it are _still_ running and should log and then die. Configuration around the number of times to do this could also be implemented to work around hung jobs.

**Comment by blueandgold** [comment]
Relates issue #1396; should also adjust the cron schedule to 12 hours, which works well for some big organizations (this should be done first).

**Comment by joecheuk** [comment]
#1446, updated the frequency of the job to every 12 hours.

**Comment by joecheuk** [comment]
Did some research, seems like we can do it in the cron job itself:
https://serverfault.com/questions/82857/prevent-duplicate-cron-jobs-running
