### ISSUE TITLE
Improve the documentation structure for installation

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#145]
- [x] Make sure that documentation is sufficient for osx/linux installations (e.g. note the libraries that are needed in osx vs linux)
- [x] Maybe try to reduce the amount of clicking through pages/links

Suggested docs structure:

* Introduction: mission statement of Forseti Security
* Installation
   * Local installation
   * Deployment to GCP
* Modules (in depth)
   * one main section per module, with sub-modules if necessary

**Comment by mirons-google** [comment]
Formatting/styling aside is there anything else to do here @carise @blueandgold

**Comment by blueandgold** [comment]
Structurally, looks better to me.  Not as much layering as before.  But each section is longer.  Is less confusion than before.  :)
Also, will we get navigation sidebars, instead of just a TOC?

**Comment by mirons-google** [comment]
Thanks. I'm going to close this for now as we have better plans in the works for the things you mention.
