### ISSUE TITLE
Don't use string literals in SQLAlchemy execute() calls

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1461]
Found Occurrences  (13 usages found)
    Unclassified occurrence  (13 usages found)
        forseti-security  (13 usages found)
            google/cloud/forseti/common/gcp_api  (2 usages found)
                _base_repository.py  (2 usages found)
                    459 return request.execute(http=self.http,
                    461 return request.execute(http=self.http,
            google/cloud/forseti/enforcer  (1 usage found)
                gce_firewall_enforcer.py  (1 usage found)
                    178 return request.execute(num_retries=4)
            google/cloud/forseti/services  (8 usages found)
                dao.py  (8 usages found)
                    504 session.execute(query)
                    507 session.execute(GroupInGroup.__table__.delete())
                    518 session.execute(qry)
                    551 rows_affected = bool(session.execute(qry).rowcount)
                    559 session.execute('UNLOCK TABLES')
                    1702 for parent, child in session.execute(qry):
                    2222 dbapi_connection.execute('pragma foreign_keys=ON')
                    2232 conn.execute('BEGIN')
           google/cloud/forseti/services/model/importer  (2 usages found)
                importer.py  (2 usages found)
                    298 self.session.execute(stmt)
                    303 self.session.execute(stmt)

**Comment by joecheuk** [comment]
Verified all the sqlalchemy execute() calls are safe from SQL Injection attack.
