### ISSUE TITLE
Use FLAGS instead of FlagValuesDict() in Inventory

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#148]
This is to be consistent with Policy Scanner and Enforcer, which uses FLAGS directly, instead of FlagValuesDict().

**Comment by carise** [comment]
I don't necessarily see this as an issue, it might actually be quite convenient to use it for the configs. :)

**Comment by carise** [comment]
I'm closing this, don't think this needs to be addressed.
