### ISSUE TITLE
Update the run_forseti script to not delete the data model

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1502]
User should be able to re use the data model created by the cron job for explain purpose. We need to clean up the data model once in a while, maybe we can follow what's implemented in Inventory (forseti inventory purge).

**Comment by blueandgold** [comment]
The new indexes has reduced the total model creation time 50X in issue #1509 .  So, that would mitigate the need to do this for 2.0

**Comment by jjawad-google** [comment]
@blueandgold is this issue still an open?

**Comment by jjawad-google** [comment]
As a result of database indexing, it is now possible to create as many data models as needed.
