### ISSUE TITLE
Consider An Easier Way to Run the Server in Debug Mode

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1511]
Currently, when doing troubleshooting, we need to stop forseti server via `systemctl` command, and then manually find the server command and then start it with the ```--log_level debug```.  It would be awesome if there's an easier workflow for this.

**Comment by joecheuk** [comment]
Now this can be done with

`forseti server log_level set <LOG_LEVEL>`
