### ISSUE TITLE
Please do not require Gsuite Super Admin for installation

### ISSUE THREAD

**Issue by rvandegrift** [GoogleCloudPlatform/forseti-security#1535]
The docs at [1] say that forseti 2.0 requires a Gsuite super admin account.  At [2], it was confirmed that the only purpose is to enable readonly access to Gsuite users and groups.

We would like to use Forseti in compliance-heavy environments where providing super admin will be unacceptable.  Please make this automated step optional.

[1] - https://docs.google.com/document/d/1RDw8QLhJVd-EAwIAviaboXwLoHPehteRGLCOXzEHBoc/preview
[2] - https://groups.google.com/a/forsetisecurity.org/d/msg/beta-testers/8gdeWG1oVSA/uyVIsctoDwAJ

**Comment by blueandgold** [comment]
@joecheuk feels that this can be done without any code changes.  Will test and update documentation, and installer if necessary with new prompt to user if they want to integrate with gsuite.

**Comment by joecheuk** [comment]
Since FS 2.0 release is coming out soon, it's safer to leave changes like these to post 2.0, will update the label to future milestone instead.

**Comment by joecheuk** [comment]
This will be updated in issue #1898

**Comment by jjawad-google** [comment]
#1898 clarifies that this is optional.
