### ISSUE TITLE
2018-05-15 11:34:43,336 ERROR google.cloud.forseti.common.util.metadata_server(_issue_http_request): Error with request: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1539]
Got this when creating inventory from 2.0-dev.

![image](https://user-images.githubusercontent.com/6977544/40076947-169e702c-5835-11e8-94ca-40afdfeebea4.png)

**Comment by joecheuk** [comment]
Seems like one of the API url is not right

![image](https://user-images.githubusercontent.com/5330393/40076988-34b99e2e-5835-11e8-9934-cbc68f1094bd.png)
