### ISSUE TITLE
Right branch to get IAM Explain module

### ISSUE THREAD

**Issue by angelzamir** [GoogleCloudPlatform/forseti-security#1586]
Hello,

I was trying to get the IAM Explain module working according to this https://forsetisecurity.org/docs/quickstarts/explain/index.html#deploying-iam-explain but it seems that the mentioned branch doesn't exist. 

Could you please tell me which branch can I use for an stable IAM Explain use. I know that it's an experimental module but I can't find the right branch for this.

Thanks in advance!

**Comment by blueandgold** [comment]
Hi, please try the 2.0-rc2 branch.
https://github.com/GoogleCloudPlatform/forseti-security/tree/2.0-rc2 branch

Please try this installation guide.
https://docs.google.com/document/d/1RDw8QLhJVd-EAwIAviaboXwLoHPehteRGLCOXzEHBoc/view

And this testing/usage guide.
https://docs.google.com/document/d/1e6uJgTZTtTCMFaZ0BMs_EtV9ULcunq-tKsNiSxIMg3M/view

**Comment by angelzamir** [comment]
Great, thanks!
