### ISSUE TITLE
Documentation for 2.0-rc3

### ISSUE THREAD

**Issue by angelzamir** [GoogleCloudPlatform/forseti-security#1612]
Hi,

Simple question, are any documents like these:

https://docs.google.com/document/d/1RDw8QLhJVd-EAwIAviaboXwLoHPehteRGLCOXzEHBoc/view#

https://docs.google.com/document/d/1e6uJgTZTtTCMFaZ0BMs_EtV9ULcunq-tKsNiSxIMg3M/view

for 2.0-rc3?

Thanks in advance.

**Comment by joecheuk** [comment]
Hi Angel,

We will send out the documentation along with the RC3 announcement early this week. 

Thanks,
Joe

**Comment by angelzamir** [comment]
Thank you so much.

**Comment by angelzamir** [comment]
Thanks! but it seems I'm not allowed to enter the group.

```
Forseti Security Beta Testers
You do not have permission to post to this group.
Return to the group's topic listing.
```

Could you give me a hand with this?

Thanks in advance!

**Comment by blueandgold** [comment]
Hi Angel, can you please join this group?

https://groups.google.com/a/forsetisecurity.org/forum/#!forum/beta-testers

Please let me know if this works.

**Comment by angelzamir** [comment]
Yeah, it works, thank you!
