### ISSUE TITLE
Installer should better handle installing by non-orgadmin.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1631]
In 2.0, the flag `--no-iam-check` is present, but is not used.  In 1.0 this had a purpose to bypass the check if the user is actually not an org admin directly, so that we can just allow groups with org admin role to run the installer.  So, check if this is necessary in 2.0, or else remove this flag.

**Comment by joecheuk** [comment]
In 2.0, if the user doesn't have access to grant some particular role(s), we will save the role granting commands into a script in the cloudshell located at ~/forseti-security and ask the user to grant the service account those roles in the script in the post installation instructions therefore this flag is no-iam-check is no longer needed.
