### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1643]
https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/rules/audit_logging_rules.yaml

![image](https://user-images.githubusercontent.com/6977544/41019469-a81cc5c8-6913-11e8-8af9-5f9156fa4210.png)

**Comment by kssrini** [comment]
Fixed Typo "exmption" to "exemption"
