### ISSUE TITLE
About GSuite service account

### ISSUE THREAD

**Issue by angelzamir** [GoogleCloudPlatform/forseti-security#1647]
Hi,

I have a simple question.
When installing Forseti from 2.0-dev branch, I can't see within the configuration or the project itself the service account for GSuite. I was looking for the `groups_service_account_key_file` property or the service account id for enabling the Domain Wide Delegation but I can't find them.

So, where I can find the config? or know how it works in 2.0-dev?

Thanks in advance!

**Comment by morgante** [comment]
@joecheuk Any insight here?

**Comment by joecheuk** [comment]
Hi there, we only have 1 service account per instance now which is the forseti gcp service account, we no longer use the account key file to do authentication, you can enable DwD on the forseti gcp server service account and Forseti should be able to get the G Suite data afterward.

**Comment by angelzamir** [comment]
Thanks!
