### ISSUE TITLE
Alpha sort the scanner maps.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1654]
Alpha sort this please!

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/scanner/scanner_requirements_map.py
![image](https://user-images.githubusercontent.com/6977544/41165407-6cb2d078-6af2-11e8-8573-96f74e94e2f7.png)

**Comment by kssrini** [comment]
Resolved #1777
