### ISSUE TITLE
Improve the docstring for iter_foo().

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1702]
The doc string of iter_foo() implies they are describing themselves as Foo Iterators, which they are not.  It would be better as something like below.  Also update documentation.

```
"""Get foo from GCP API."""
```

```
docs/latest/develop/dev/inventory.html
```

https://github.com/GoogleCloudPlatform/forseti-security/blob/stable/google/cloud/forseti/services/inventory/base/gcp.py#L595-L606
```python
    @create_lazy('compute', _create_compute)
    def iter_images(self, projectid):
        """Image Iterator from gcp API call
        Args:
            projectid (str): id of the project to query
        Yields:
            dict: Generator of image resources
        """
        for image in self.compute.get_images(projectid):
            yield image
```

**Comment by kssrini** [comment]
Updated docstring for iter_foo and fecth_foo #1702
