### ISSUE TITLE
Forseti Server 2.0  Not Starting 

### ISSUE THREAD

**Issue by santhh** [GoogleCloudPlatform/forseti-security#1712]
Hello everyone:
I am trying to help a client setup forseti 2.0 RC3. I can successfully install in my org and project but ran into some issues while trying in client org. 

What we are noticing, after forseti_conf_server.yaml is updated with gsuite-service_account_key_file and cscc integration properties- server does not start. In the forseti log, there is no error message but it seems stuck in a compile step (model.proto). Can you help with this issue or guide us with troubleshoot steps?  Please let me know if you need more information. I have  a screen shot of the forseti log.  Deployment log says it's successful.Thanks.
![screen shot 2018-06-22 at 1 49 33 pm](https://user-images.githubusercontent.com/27572451/41862833-ff6defbe-7872-11e8-913d-7491785ad293.png)

sudo systemctl status forseti.service   shows server failed. 
![screen shot 2018-06-22 at 1 48 12 pm](https://user-images.githubusercontent.com/27572451/41863027-939fdd14-7873-11e8-894a-08f636f9a200.png)

**Comment by joecheuk** [comment]
Resolved offline, will close this issue for now. If you experience the same problem again, feel free to re-open it.

**Comment by deepakmahajan-23** [comment]
facing the same issue above not starting the forseti server..please help

**Comment by emilva** [comment]
@joecheuk please post the details in this thread
