### ISSUE TITLE
Automate service account creation

### ISSUE THREAD

**Issue by jay0lee** [GoogleCloudPlatform/forseti-security#174]
The new Cloud APIs allow automation of much of the work to setup a service account making new user onboarding easier. Here's what I'd recommend:

1. Create the API project: https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/create
    * user may need to accept ToS before project will create. API does not currently return URL to accept ToS but https://console.cloud.google.com/start seems to work for my users.

2. Enable necessary APIs for project (Admin SDK, etc) for the project: https://cloud.google.com/service-management/reference/rest/v1/services/enable

3. Create the service account: https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/create

4. Create the private key for project: https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts.keys/create
      * It'd be nice here if the API let us create the private key locally and just upload the public key to Google. That way the private key never needs to cross the Internet which increases security. Not possible today afaik but should ask Cloud team

5. Enable Domain Wide Delegation. Currently manual. I direct users to:
   https://console.developers.google.com/apis/credentials?project=<projectid>
   and list manual steps to turn on DwD.

**Comment by carise** [comment]
Hey @jay0lee, sorry for the late response to your suggestions -- these are great! We are planning to do something about automating the steps for Forseti setup and plan to take your advice into account as well.

**Comment by carise** [comment]
#338 setup wizard helps with this
