### ISSUE TITLE
Ensure we have stacktrace in broad excepts.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1797]
In places where we are using broad excepts, we must ensure that the stacktrace of the exception is captured, so that we know where the exception is originating from.

Currently, we have this, which is hard to see where the problem is:
`LOGGER.error(e)`
![image](https://user-images.githubusercontent.com/6977544/42797435-12d789f2-8944-11e8-8b69-4465d59428d8.png)

By having the stacktrace, we can easily see where the problem is:
`LOGGER.error(traceback.print_exc())`
`LOGGER.exception(e)`
![image](https://user-images.githubusercontent.com/6977544/42797373-cebfcab8-8943-11e8-9815-13e6f7f5e3f5.png)

**Comment by jjawad-google** [comment]
Resolved in #1836
