### ISSUE TITLE
Shorten hash produced by _create_violation_hash()

### ISSUE THREAD

**Issue by mcapts** [GoogleCloudPlatform/forseti-security#1802]
Using the latest dev branch, Cloud SCC is returning 500 errors due to the violation hash being too long. Cloud SCC is working on fixing this, but in the interim, @blueandgold and I have determined a 64 character hash does not produce the same errors. This should be sufficient to uniquely represent violations, but please verify before implementing.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/forseti/services/scanner/dao.py#L371

We appended [:64] to the end of this return line, but that might just be truncating a larger hash and risk collision, so please investigate before implementing this.

**Comment by rgmenon** [comment]
We are relying on the current hash to determine uniqueness of violations and so this will break how we detect new violations.

**Comment by blueandgold** [comment]
Thanks Ramesh for letting us know your use case.  I will think about an alternate way of doing this, and make sure the change (somewhere) will work out for everyone.  :)

**Comment by blueandgold** [comment]
Fixed by #1803
