### ISSUE TITLE
Update the website to take advantage of the git_repo param

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1816]
Our docs could be simplified by offering a link to open a cloud shell and clone the repo right away with a URL like the one below.

https://console.cloud.google.com/cloudshell/open?git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fforseti-security&page=editor

**Comment by EricBeach** [comment]
@mirons-google - if there are some places in the docs where you want these links, let me know either the specific URLs or conceptually where, and I can take care of this.

**Comment by EricBeach** [comment]
@mirons-google - any guidance on specific locations or types of locations where I should do this?

**Comment by EricBeach** [comment]
From chatting offline with Mike:
https://forsetisecurity.org/docs/latest/setup/install.html#activate-google-cloud-shell
the first few steps of the next section could be replaced with one link
similar documentation in the upgrade and manual guides too

**Comment by EricBeach** [comment]
After talking with @blueandgold  we're going to pass on implementing this.
