### ISSUE TITLE
Upgrade tool needed for Forseti 2.0

### ISSUE THREAD

**Issue by jjawad-google** [GoogleCloudPlatform/forseti-security#1826]
#1806 

Substantial amount of effort required (1 eng mo). Upgrade process should also work with Terraform. In the meantime, mention to users to follow manual upgrade process.

**Comment by blueandgold** [comment]
Things to think about:

- Understand volume of customers who are using a feature that are about to break. That way we can forecast how big a deal this change is likely to be.
- Need to give lots of notice on breaking changes in general. What kind of notice window do we think is right?
- How do we minimize breaking changes that might happen a few times in a row? Can we group these up?

**Comment by blueandgold** [comment]
This tool would have helped to manage an upgrade breaking change in #1982.

**Comment by hshin-g** [comment]
Addressed by [Forseti Terraform installer](https://github.com/terraform-google-modules/terraform-google-forseti).
