### ISSUE TITLE
Restarting Forseti instance should automatically pickup patches

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1827]
Since patches are only related to bug fixes, we should always make sure by restarting the instance, users are able to get the latest changes instead of having them going through the upgrade process with deployment manager.

e.g. 
if user is on 2.0.0 and we released a 2.0.1 patch, by restarting the instance, we should automatically upgrade the version to 2.0.1.

**Comment by blueandgold** [comment]
@osandoval011 can you please link to your PR and close this?

**Comment by osandoval011** [comment]
#2469
