### ISSUE TITLE
Forseti inventory stopped running after a day or two due to auth problem

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1832]
Error message:

> Error occurred on the server side, message: <_Rendezvous of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "Exception iterating responses: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials."
>         debug_error_string = "{"created":"@1533055140.251333959","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"Exception iterating responses: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.","grpc_status":2}"
> >
>

**Comment by mcapts** [comment]
Is this still being worked on? This is causing my crontab to fail, which means I needed to add instance reboot logic. I got the latest version of the dev branch (today) but it is still failing without a reboot.

**Comment by blueandgold** [comment]
@mcapts This is indeed being worked on.  We escalated this to the google.auth library team and they are working to resolve it on their side.  In the meantime, we have added this as a workaround. Can you use this?
https://github.com/GoogleCloudPlatform/forseti-security/pull/1940/files

**Comment by mcapts** [comment]
Thanks @blueandgold ! I added some code to restart the forseti service on my server for now.

**Comment by blueandgold** [comment]
Investigation is revealing that the `set_user_agent()` in the `google-api-python-client` library is repeatedly causing the header to grow and fail.  Opened issue #2090 to fix.

**Comment by blueandgold** [comment]
I have verified this is work; VM with the fix has been running like a champ for over 5 days.
