### ISSUE TITLE
Database error with Firewall rules

### ISSUE THREAD

**Issue by raja-akula97** [GoogleCloudPlatform/forseti-security#1866]
Hi! There is an error with the parsing the fullname. There should be a '/' after the folder_id.

<img width="222" alt="screen shot 2018-08-08 at 11 57 47 am" src="https://user-images.githubusercontent.com/23041953/43852228-51839630-9b02-11e8-9698-eb78ab00bf4e.png">

**Comment by joecheuk** [comment]
Hi @raja-akula97 , thanks for opening the issue, this issue has been reported and fixed by @jceresini , we will be including the fix in the upcoming release.

https://github.com/GoogleCloudPlatform/forseti-security/issues/1703

**Comment by blueandgold** [comment]
Verified to be working.
