### ISSUE TITLE
Data model is broken

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1868]
One of our customers reported the error, with ~1 million inventory objects

> Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forse
ti/services/model/importer/importer.py\", line 283, in run\n    1000\n  File \"/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.eg
g/google/cloud/forseti/services/model/importer/importer.py\", line 332, in model_action_wrapper\n    for idx, inventory_data in enumerate(inventory_i
terable, start=1):\n  File \"/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.
py\", line 879, in iter\n    for row in base_query.yield_per(PER_YIELD):\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py\", line 98,
 in instances\n    util.raise_from_cause(err)\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py\", line 265, in raise_from_cause\n    
reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py\", line 71, in instances
\n    fetch = cursor.fetchmany(query._yield_per)\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py\", line 1166, in fetchmany\n    s
elf.cursor, self.context)\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py\", line 1413, in _handle_dbapi_exception\n    exc_info\n  
File \"build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py\", line 265, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, ca
use=cause)\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py\", line 1159, in fetchmany\n    l = self.process_rows(self._fetchmany_i
mpl(size))\n  File \"build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py\", line 1318, in _fetchmany_impl\n    row = self._fetchone_impl()\n  Fi
le \"build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py\", line 1308, in _fetchone_impl\n    self.__buffer_rows()\n  File \"build/bdist.linux-x
86_64/egg/sqlalchemy/engine/result.py\", line 1295, in __buffer_rows\n    self.__rowbuffer = collections.deque(self.cursor.fetchmany(size))\n  File \
"build/bdist.linux-x86_64/egg/MySQLdb/cursors.py\", line 441, in fetchmany\n    r = self._fetch_row(size or self.arraysize)\n  File \"build/bdist.lin
ux-x86_64/egg/MySQLdb/cursors.py\", line 327, in _fetch_row\n    return self._result.fetch_row(size, self._fetch_type)\nOperationalError: (_mysql_exc
eptions.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8)\n",
  "createdAt": "07 August 2018 - 11:11:11",
  "description": "{\"pristine\": true, \"source\": \"inventory\", \"source_root\": \"organization/1234567891234\", \"gsuite_enabled\": false, \"source
_info\": {\"inventory_index_id\": 123456789123456789}}"

**Comment by joecheuk** [comment]
Based on the documentation from the mysql site: https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html

We can try increasing the timeout by modifying the **net_read_timeout** variable

>> Sometimes the “during query” form happens when millions of rows are being sent as part of one or more queries. If you know that this is happening, you should try increasing net_read_timeout from its default of 30 seconds to 60 seconds or longer, sufficient for the data transfer to complete.

If that doesn't solve the problem then we can try increasing the **max_allowed_packet** variable and see if the packet size was the main cause.

>> If the cause is none of those just described, you may be experiencing a problem with BLOB values that are larger than max_allowed_packet, which can cause this error with some clients. Sometime you may see an ER_NET_PACKET_TOO_LARGE error, and that confirms that you need to increase max_allowed_packet.

**Comment by joecheuk** [comment]
Google Cloud SQL doesn't seem to support flag **net_read_timeout**, maybe we will need to break down that session into multiple smaller chunks.

https://cloud.google.com/sql/docs/mysql/flags

**Comment by ocervell** [comment]
Maybe we can change the `pool_recycle` parameter to a lower value [here ](https://github.com/GoogleCloudPlatform/forseti-security/blob/6249e00acf931e7846dbe905abcb85ed424ff8f8/google/cloud/forseti/services/base/config.py#L254)?
From [sqlalchemy docs](http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle):
"This parameter prevents the pool from using a particular connection that has passed a certain age, and is appropriate for database backends such as MySQL that automatically close connections that have been stale after a particular period of time"

**Comment by jjawad-google** [comment]
@joecheuk do you have an update ? Please reprioritize to P0 if more customers are affected.

**Comment by jjawad-google** [comment]
Customer has cleaned up their environment and is no longer observing the issue.
