### ISSUE TITLE
CronJob runs forever. No new Job is executed

### ISSUE THREAD

**Issue by starketin** [GoogleCloudPlatform/forseti-security#1880]
Hi!

I'm running forseti V2.1.0 setup with the deployment script through cloud shell. 
The cronjob is the default one and is running every 2 hours. Unfortunately it gets stuck after some executions.
If I do a 
``` bash
ps -ef
ubuntu   19415 19414  0 Aug10 ?        00:00:00 /bin/sh -c (/usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh || echo '[forseti-security] Warning: New Forseti
ubuntu   19416 19415  0 Aug10 ?        00:00:00 /bin/sh -c (/usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh || echo '[forseti-security] Warning: New Forseti
ubuntu   19417 19415  0 Aug10 ?        00:00:00 logger
ubuntu   19419 19416  0 Aug10 ?        00:00:00 /usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh
ubuntu   19420 19419  0 Aug10 ?        00:00:00 /bin/bash /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh
ubuntu   19810 19420  0 Aug10 ?        00:00:59 /usr/bin/python /usr/local/bin/forseti inventory create --import_as 20180810T140518
```
you can see that it stopped working at 20180810T140518 (now its 20180813T081100) 

After that I get the log messages saying that it didn't run because it's already running. 

This is possibly related to these existing issues here: 
https://github.com/GoogleCloudPlatform/forseti-security/issues/1548
https://github.com/GoogleCloudPlatform/forseti-security/issues/1844

If the issue can't be fixed right away, a workaround like killing the longrunning task would be nice 😎 

Thanks Simon

**Comment by joecheuk** [comment]
Hi Simon,

I think this issue might be related to #1832, can you try running command `forseti inventory list` and see if you see a bunch of inventories with STATUS=FAILURE? The temporary solution to that is to restart the server once in a while by running command `sudo systemctl restart forseti.service` until we have the solution implemented.

Thanks,
Joe

**Comment by starketin** [comment]
Hi Joe,

There are a bunch of inventorys with FAILURE and 0 seconds execution time. Before that there are some with success and no errors and than I get the a sucessful inventory with a lot of errors reagarding GOOGLE_ACCOUNT_CREDENTIALS. If you are interested in logs or more details let me know.

Will try with regular service restart as long as the PR you have is not available.

Thanks Simon

**Comment by joecheuk** [comment]
Hi @starketin ,

We have released a patch to restart the Forseti server before every cron job, if you are on version v2.1.0, you can reset the VM to pick up the patch. 

Feel free to re-open this issue if the problem still exists after the update.

Thanks,
Joe
