### ISSUE TITLE
Installing with 2.1 and Shared VPC

### ISSUE THREAD

**Issue by bkudzia** [GoogleCloudPlatform/forseti-security#1894]
- Using 2.1
 - General installation help
 - SSH to tail instance install logs fails, firewall rule creation fails, was unable to run an inventory after deployment finished
 - Deployment Manager

Hello,

I was attempting to install v2.1 with a customer today who is using a shared VPC.  We were able to use the switches in the installer to set the host project, host vpc, and subnet, but several things went awry:

1)  The SSH commands to tail the compute instance install logs fails during deployment
2)  The firewall rule creations all fail
3)  After deployment completed, customer was unable to run an inventory due to a general "failed to communicate with server" error, even though we were running things on the server VM

I believe #1 is caused by #2, and my hunch for #2 is that the firewall rules need to be created in the host project rather than the service project, and cross-project deployments are complex.  I'm not sure if this can be fixed easily, but would be open to manual workarounds just to get customers up and running, if possible.

I was not able to figure out the reason for #3, nor get it to work in this case.  If there's anything you can offer for us to check or try, I can take a look next time I have time with the customer.  I manually created the SSH and GRPC firewall rules, but that did not fix it.

I will be doing some testing myself to see if I can reproduce or get around these problems.  I will post any relevant and/or useful info I come up with.

Thank you!

**Comment by blueandgold** [comment]
@bkudzia Installing with VPC is currently not in 2.1.  However, it is implemented recently #1874 , and will be released in the upcoming 2.2 version of Forseti.

**Comment by bkudzia** [comment]
Ok.  Makes sense based on what I've been seeing.  Adding an allow ssh rule fixes the install log tail timeout during deployment, and I'll have to create the three forseti firewall rules in the host project manually for now.  I will keep an eye out for 2.2 and retry at that point.  Thanks.

**Comment by blueandgold** [comment]
Shared VPC support is already out.  Please let us know if you have any more issues with this.
