### ISSUE TITLE
Remove "sample" from cloudsql rules

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1908]
Although they do serve as sampling purpose, they are also actual valid rules and should not have `sample` in the actual name.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/rules/cloudsql_rules.yaml
```
name: sample Cloud SQL rule to search for publicly exposed instances
name: sample Cloud SQL rule to search for publicly exposed instances (SSL enabled)
```

**Comment by blueandgold** [comment]
There are other rules with `sample` in the name as well.  Please look through all the rule files, and fix.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/rules/bigquery_rules.yaml

**Comment by red2k18** [comment]
Removed "sample" from all the rules.
