### ISSUE TITLE
Forseti Installer Error

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1910]
This is likely from the change in #1874   @johnrevans6 

![image](https://user-images.githubusercontent.com/6977544/44321073-c100b280-a3fa-11e8-8c74-e422970370a6.png)

**Comment by johnrevans6** [comment]
Hmmm I haven't encountered this before. I'll see if I can't dig into it tomorrow.

**Comment by johnrevans6** [comment]
Actually, I think I see the issue. Looks like I missed removing the method call to get_project. That method call shouldn't be necessary unless I'm missing something.

**Comment by ocervell** [comment]
I'm encountering the same issue - https://gist.github.com/ocervell/2761defcd4770493d820c08295457cf9

I've replaced `self.get_project()` by `self.project_id, _, _ = get_gcloud_info()` and it fixed it.

**Comment by ocervell** [comment]
Actually, seems like we also need:

`self.config.vpc_host_project_id = self.project_id`

otherwise the installer fails with [this error](https://gist.github.com/ocervell/109a0501037dd0a4dbe454648f4b31d9)

**Comment by johnrevans6** [comment]
You should only need to set the VPC's host project. The rest of that check is superfluous as it pertains to VPC. @ocerveil can you provide more detailed reproduction steps? I'd like to reproduce and make sure nothing else was left in from the previous PR.

**Comment by johnrevans6** [comment]
Ah, nevermind. I see what you're saying now. Makes more sense when I'm not on a 6" screen. Yeah, so the command check should read:

self.vpc_host_project_id, _, _ = get_gcloud_info()

- OR -

self.project_id, _, _ = get_gcloud_info()
self.vpc_host_project_id = self.project_id

Which do we prefer here?

**Comment by ocervell** [comment]
If you look at my previous comment, I also had to set `self.config.vpc_host_project_id` and not just `self.vpc_host_project_id` for some reason. Seems like the config one is being picked up somewhere else.

**Comment by ocervell** [comment]
First syntax looks good.
I also think we're calling `set_network_host_project` only for the server install (in `preflight_checks`) but (correct me if I'm wrong) not for the client install, so we need to check that as well.

**Comment by ocervell** [comment]
If we need the `set_network_host_project()` call for server and client, then we could put it into the `__init__` of `install/gcp/installer/forseti_installer.py` to avoid redundancy

**Comment by johnrevans6** [comment]
Hmmm, can you clarify why setting the VPC's host project would be necessary to do at the Client Installer?  The purpose of the check is to ensure that the self.config.vpc_host_project_id is set before attempting to proceed with the installation. That variable exists at the Config level, and so it should be accessible by both the Server and the Client. Right?

**Comment by ocervell** [comment]
The client uses this variable in the deployment template as well: https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/deployment-templates/deploy-forseti-client.yaml.in

The `deploy` step in the client installer fails as well right now if we're not setting this variable.

**Comment by johnrevans6** [comment]
Correct. But this:

self.vpc_host_project_id, _, _ = get_gcloud_info()

Ensures the variable is set as part of the preflight checks.

**Comment by ocervell** [comment]
`preflight_checks` are run only for the server install but not for the client install, hence my idea of putting the call into the `__init__` of the base class instead.

**Comment by ocervell** [comment]
Nevermind, you're right, `preflight_checks` will be run as part of the `run_setup`.

The real problem here is that it will fail if you run both the server and client installs after each-other:

`run_setup` --> `preflight_checks` will be called for the server install, but not for the client install (because continuation is set to `false`, and so `self.config.vpc_host_project_id will not be set for the client)

**Comment by johnrevans6** [comment]
Meaning, running the server, and then run the client as separate installs? I actually forgot you can do that. Then yeah, placing it in the __init__ of the Forseti Installer itself makes the most sense.

**Comment by ocervell** [comment]
Yeah, basically:

`python install/gcp/gcp_installer.py --type=server` will succeed
`python install/gcp/gcp_installer.py --type=client` will succeed

but:
`python install/gcp/gcp_installer.py` will fail because `self.config_vpc_host_project_id` is not set (because the `preflight_checks` are skipped for the client since `continuation` is set)

**Comment by ocervell** [comment]
I'll make a PR with the change shortly since it's already there on my repo

**Comment by johnrevans6** [comment]
Sounds good!
