### ISSUE TITLE
Can't deploy with 2.1 installer today 8.21.18

### ISSUE THREAD

**Issue by bkudzia** [GoogleCloudPlatform/forseti-security#1923]
- [ ] 2.1
 - [ ] Install fails at deployment creation stage
 - [ ] Seeing this:

+-------------------------------------------------------------------------------
|  Creating Forseti Server Deployment
+-------------------------------------------------------------------------------

Deployment name: forseti-server-17cdcac
Monitor the deployment progress here: https://console.cloud.google.com/deployments/details/forseti-server-17cdcac?project=<REMOVED>&organizationId=<REMOVED>

Waiting for deployment to be completed... {u'errors': [{u'message': u"Manifest expansion encountered the following errors: Invalid properties for 'forseti-instance-server.py':\n'service-account-gsuite' is a required property\n Resource: forseti-instance-server Resource: config", u'code': u'MANIFEST_EXPANSION_USER_ERROR', u'location': u'/deployments/forseti-server-17cdcac/manifests/manifest-1534869204345'}]}

 - [ ] Trying to use the 2.1 installer

I had a copy of the installer files from 8.16.18, and that deploys just fine in the same project with the same user with the same switches (using vpc host and network arguments when running the install).  I couldn't find any major differences between those files the new ones I cloned down today, so I'm not sure what's causing this.  Just FYI, as I can use the older files to deploy for now.

**Comment by joecheuk** [comment]
Hi @bkudzia , can you try pulling from the "dev" branch and run the installation again? This seems to be an issue addressed in a previous PR.

**Comment by joecheuk** [comment]
Hi @bkudzia , this issue should now be fixed on the dev branch, feel free to re-open this issue if it occurs again.

**Comment by bkudzia** [comment]
Ok, cool.  Will give it a test as soon as i can get a cloud shell vm.  Thanks!

**Comment by bkudzia** [comment]
Yep, looks like it's all good now.  Thank you.

**Comment by joecheuk** [comment]
Thanks for the updates!
