### ISSUE TITLE
Duplicate SSH Firewall Rule is Created by Installer

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1973]
The ssh firewall rule created by the installer is almost the same as the default ssh rule, except it's targeted to the service account and higher priority.  

Also, the deny-all created by the installer also seems be the same as the `implied deny ingress rule`.

After discussing with @ahoying, the default firewall rules in the project should be removed.

https://cloud.google.com/vpc/docs/firewalls

![image](https://user-images.githubusercontent.com/6977544/44831120-f3b86100-abd9-11e8-8371-e4c75ff13e11.png)

**Comment by red2k18** [comment]
Deleted default firewall rules for testing, was able to run Forseti and SSH into the client/server VM. Seems functionality doesn't change by deleting default rules. Going to add a method to delete default firewall rules from the project to avoid any confusion thereby making concepts clearer for the users. Will add an FAQ as well.
