### ISSUE TITLE
Typos on site documentation

### ISSUE THREAD

**Issue by davidlauen** [GoogleCloudPlatform/forseti-security#1974]
I found a few minor typos on your forsetisecurity.org site. 

https://forsetisecurity.org/docs/latest/develop/website.html

Paragraph at the top of the page. 

The instructions below are aimed at developers using Linux, particularly Debian or Ubuntu. This **_pages shows_** you how to install and run the website server _**lcoally**_, so that you can test your documentation changes before merging.

**Comment by red2k18** [comment]
- [ testing ]

**Comment by red2k18** [comment]
# [checkbox: testing]
