### ISSUE TITLE
Define How to Do Upgrade Testing

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1995]
We are including the testing of various upgrade paths into our release process in order to avoid upgrade issues like #1982 which causes a breaking change by Deployment Manager's limitation that we did not know about.

We should define how to do the testing, for various upgrade paths like this:
```
2.1.0 -> 2.2.0 
2.1.0 -> 2.3.0
2.2.0 -> 2.3.0
```

**Comment by joecheuk** [comment]
We have defined upgrade testing in our documentation.
https://forsetisecurity.org/docs/latest/setup/upgrade.html
