### ISSUE TITLE
Improve Naming Quality of the Docker Setup and Install Scripts

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1996]
From the update in #1993, we need to make the scripts' naming align with the documentation, where the `install` is confusing with `setup`, and `install` is really doing starting or running.

The smallest change would be to change:
current: `install/scripts/docker_install_forseti.sh`
proposed: `install/scripts/docker_run_forseti.sh`

![image](https://user-images.githubusercontent.com/6977544/45244898-a52c5600-b2ae-11e8-9de1-c4831fe6b9b0.png)

**Comment by jjawad-google** [comment]
#1998

**Comment by blueandgold** [comment]
This is fixed by @rvandegrift
