### ISSUE TITLE
Gap Analysis of CIS Recommendations for Better Security on GCP

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2007]
The Center for Internet Security (CIS) has published recommendations for better security on GCP.  
`Google Cloud Platform Foundation v1.0.0 09-05-2018`

It would be great if we can analyze those against the coverage provides by Forseti, and see where are the gaps so that we fill them in in a prioritize fashion.

**Comment by jjawad-google** [comment]
We will investigate internally.

**Comment by Red-Five** [comment]
Customers are asking for CIS coverage.

Can we publish the CIS Gap Analysis (on github or forsetisecurity.org) in such a manner that the community can see gaps and collaboratively work on closing them?

**Comment by ryanismert** [comment]
I'll commit to cleaning it up and getting it published to the website by 5/1.
