### ISSUE TITLE
Add support for project liens

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2010]
We would like Forseti to be able to check for the existence and correct configuration of project liens.

**Comment by umairidris** [comment]
Still need to add scanner :)

**Comment by joecheuk** [comment]
If you reference the issue in your PR with certain wordings (maybe fix is one of them?), it will close the issue automatically when the PR is closed - I didn't close it manually :)

**Comment by umairidris** [comment]
Today I learned... will keep that in mind
