### ISSUE TITLE
Scanner should support GSuite Google Groups inventories

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#202]
Groups (if enabled) are stored in groups_<timestamp> and group_members_<timestamp> accordingly.

**Comment by blueandgold** [comment]
First PR #268 to support whitelisting.

**Comment by blueandgold** [comment]
Whitelist support is in #268 and #275.  Blacklist and required members are still pending.

**Comment by blueandgold** [comment]
Will wait until there are user needs for the blacklist & required members.
