### ISSUE TITLE
Always include Scanner Rule Name in Violation

### ISSUE THREAD

**Issue by mcapts** [GoogleCloudPlatform/forseti-security#2022]
For example, Group violations include the violated_rule_name field, but Enabled APIs violations do not. I believe we should standardize on certain information being included in the violation, such as the rule name, so that the alerting systems that ultimately parse and track violations that Forseti finds make the source/meaning of the violation more clear.

**Comment by red2k18** [comment]
Verified that rule name is included in the violations for Enabled APIs scanner as well.

**Comment by red2k18** [comment]
RuleViolation(resource_type='project', resource_id='ahoying-forseti-dev', full_name='organization/660570133860/project/ahoying-forseti-dev/', rule_name='Example Enabled APIs whitelist', rule_index=0, violation_type='ENABLED_APIS_VIOLATION', apis=(u'bigquery-json.googleapis.com', u'clouddebugger.googleapis.com', u'storage-component.googleapis.com', u'pubsub.googleapis.com', u'container.googleapis.com', u'storage-api.googleapis.com', u'logging.googleapis.com', u'resourceviews.googleapis.com', u'replicapool.googleapis.com', u'deploymentmanager.googleapis.com', u'containerregistry.googleapis.com', u'monitoring.googleapis.com', u'compute.googleapis.com', u'sql-component.googleapis.com', u'cloudtrace.googleapis.com', u'servicemanagement.googleapis.com', u'replicapoolupdater.googleapis.com'), resource_data='[{"producerProjectId": "google.com:ultra-current-88221", "serviceName": "bigquery-json.googleapis.com"}, {"producerProjectId": "google.com:cloud-debugger-producer", "serviceName": "clouddebugger.googleapis.com"}, {"producerProjectId": "crm-api-producer-project", "serviceName": "cloudresourcemanager.googleapis.com"}, {"producerProjectId": "cloud-datastore-api", "serviceName": "datastore.googleapis.com"}, {"producerProjectId": "google.com:prod-default-producer-project", "serviceName": "storage-component.googleapis.com"}, {"producerProjectId": "cloud-pubsub-billing", "serviceName": "pubsub.googleapis.com"}, {"producerProjectId": "google.com:cloud-kubernetes-devrel", "serviceName": "container.googleapis.com"}, {"producerProjectId": "cloud-storage-producer", "serviceName": "storage-api.googleapis.com"}, {"producerProjectId": "metal-incline-93520", "serviceName": "logging.googleapis.com"}, {"producerProjectId": "google.com:prod-default-producer-project", "serviceName": "resourceviews.googleapis.com"}, {"producerProjectId": "google.com:api-project-861046436738", "serviceName": "replicapool.googleapis.com"}, {"producerProjectId": "google.com:api-project-73174915157", "serviceName": "admin.googleapis.com"}, {"producerProjectId": "google.com:api-project-596022999904", "serviceName": "deploymentmanager.googleapis.com"}, {"producerProjectId": "cloud-billing-api", "serviceName": "cloudbilling.googleapis.com"}, {"producerProjectId": "containerregistry", "serviceName": "containerregistry.googleapis.com"}, {"producerProjectId": "google.com:manifest-emblem-349", "serviceName": "sqladmin.googleapis.com"}, {"producerProjectId": "google.com:gcm-api-admin", "serviceName": "monitoring.googleapis.com"}, {"producerProjectId": "google.com:google-services", "serviceName": "oslogin.googleapis.com"}, {"producerProjectId": "google.com:api-project-539346026206", "serviceName": "compute.googleapis.com"}, {"producerProjectId": "google.com:elegant-theorem-93918", "serviceName": "appengine.googleapis.com"}, {"producerProjectId": "google.com:manifest-emblem-349", "serviceName": "sql-component.googleapis.com"}, {"producerProjectId": "iam-whitelisting-project", "serviceName": "iam.googleapis.com"}, {"producerProjectId": "cloud-trace-api-producer", "serviceName": "cloudtrace.googleapis.com"}, {"producerProjectId": "google.com:steel-binder-818", "serviceName": "servicemanagement.googleapis.com"}, {"producerProjectId": "iam-credentials-prod", "serviceName": "iamcredentials.googleapis.com"}, {"producerProjectId": "google.com:prod-default-producer-project", "serviceName": "replicapoolupdater.googleapis.com"}]', resource_name=None)
