### ISSUE TITLE
Model Delete output is.. sparse?

### ISSUE THREAD

**Issue by MartenvanWezel** [GoogleCloudPlatform/forseti-security#2032]
Using Forseti 2.3

`forseti-client-vm-b8d78ec:~$ forseti model delete test

{}`

perhaps at least return a status?

**Comment by jjawad-google** [comment]
Need to determine what sort of info needs to be passed back in the response and gauge difficulty.

**Comment by red2k18** [comment]
Model Delete command now returns success or failure message based on whether model is deleted or not.
