### ISSUE TITLE
Resource and scanner docs are scarce

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2042]
Adding a resource and scanner is very involved. The current documentation is not sufficient to implement one (https://forsetisecurity.org/docs/latest/develop/dev/scanner.html). 

#2041 contains a full self contained example. Perhaps this can be linked in the docs or the docs can be updated to suggest all the steps.

**Comment by blueandgold** [comment]
Thanks Umair for raising this.  This relates to #1957.

**Comment by umairidris** [comment]
Ah, great. Considering it's already in the works I'll close this as duplicate.
