### ISSUE TITLE
Update Documentation for CloudAsset

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2052]
Please document the changes associated with changes in #2008, #2019, , #2028, #2034.

These are primarily:
- new permission
- new api
- how to upgrade (such the quota, and cai, in the server config)

**Comment by jjawad-google** [comment]
@red2k18 could you link the PR for this issue + close?

**Comment by red2k18** [comment]
@jjawad-google This issue is closed in PR #2054
