### ISSUE TITLE
Checking VM initialization failed during the installation process.

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#2070]
+-------------------------------------------------------------------------------
|  Forseti Server VM Initialization
+-------------------------------------------------------------------------------

Error occurred when sshing to the VM.  Unable to verify if the VM is fully initialized. This is a non-fatal error, but you should verify the VM is fully initialized before use. You can do so by SSHing to the VM, run command "tail -n1 /tmp/deployment.log" and make you get "Execution of startup script finished" in response. Will skip waiting for the instance to be initialized and proceed with the rest of the installation.
Updating project ssh metadata...
......................Updated [https://www.googleapis.com/compute/v1/projects/xxxxxxxxxx].
done.
Waiting for SSH key to propagate.
Warning: Permanently added 'compute.8493611379865452775' (ECDSA) to the list of known hosts.

**Comment by jjawad-google** [comment]
@red2k18 was this issue observed during the v2.6.0 release?

**Comment by blueandgold** [comment]
I did a new install and this is not happening anymore.
