### ISSUE TITLE
Separate active/pending delete project status in inventory summary email

### ISSUE THREAD

**Issue by davidlauen** [GoogleCloudPlatform/forseti-security#2094]
First, help us help you by providing the following information when opening an issue.

 - [ 2.5] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
 - [notifier ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.

It would be nice to see a separate line item in the inventory output email for project counts to distinguish between active projects (like CSCC counts) and pending delete projects. Currently I do not have an accurate count of projects pending delete.

**Comment by hshin-g** [comment]
PR created and merged into dev to address issue.
