### ISSUE TITLE
Error during scanning from non-existent scanner is not obvious

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2096]
To reproduce:
- in forseti_conf_server.yaml, add a scanner that does not exist
- reset the server
- ssh into the forseti client
- run the following commands on client:
```
  $ MODEL_NAME=$(/bin/date -u +%Y%m%dT%H%M%S)
  $ forseti inventory create --import_as ${MODEL_NAME}
  $ forseti model use ${MODEL_NAME}
  $ forseti scanner run
```
- observe the scanner failing, with no useful information as to why.
> {
>   "serverMessage": "Error occurred during the scanning process."
> }
> 
- observe forseti server and client stackdriver logs having no indication as to why it failed as well (no stack, no error message, etc).

> I  [forseti-security][2.4.0] google.cloud.forseti.services.scanner.service(Run): Run scanner service with model: 2020659dff6451acffd7df8372dd5304 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/bigquery_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/blacklist_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/bucket_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/cloudsql_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/firewall_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/group_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/iam_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/iap_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/ke_rules.yaml 
> I  [forseti-security][2.4.0] google.cloud.forseti.scanner.scanner_builder(build): Initializing the rules engine:
> Using rules: /home/ubuntu/forseti-security/rules/lien_rules.yaml 
> A  Oct 16 16:07:07 forseti-server-vm-8e2ebac systemd[1]: Starting Cleanup of Temporary Directories... 
>

**Comment by angelsungoogle** [comment]
Please see PR #2160 for details of the revision, and let me know if you have any questions.

Angel
