### ISSUE TITLE
Model on a previous version silently fails to report violations

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2098]
To reproduce:
- Create inventory in forseti client VM:
$ MODEL_NAME=$(/bin/date -u +%Y%m%dT%H%M%S)
$ forseti inventory create --import_as ${MODEL_NAME}
$ forseti model use ${MODEL_NAME}

- Update forseti version (or sync to a point after which forseti version changed)
- Run scanners and notifier:
$ forseti scanner run
$ forseti notifier run

Observe that while the scanner runs succesfully and finds violations, the notifier does not actually write them to the gcs buckets. There is no error or log to indicate why, but recreating the model solves the issue (at latest version).

**Comment by blueandgold** [comment]
Hi @umairidris, after an upgrade to a new version, it would be advisable to re-create & re-run everything on the new version as data structure and code behavior could have changed.  From a user experience's point of view, it would be nice to handle & warn this for the user.  If you feel this is important, please re-open this issue.  Thanks!
