### ISSUE TITLE
Thread exception when collecting inventory or running scanner

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2109]
On our production forseti instance I see the following error at the end of inventory collection or scanner runs:

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 706, in channel_spin
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 173, in handle_event
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get_fork_epoch'

Doesn't seem to be causing any issues from what I can tell, but not certain.

**Comment by ahoying** [comment]
umairidris@: Can you verify that your version of grpc is update to date? How did you deploy forseti? Are there additional logs related to the error you are seeing?

This error is from deep in the grpc code, https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L174, it's hard to tie back to a specific problem in Forseti without additional details.

**Comment by ahoying** [comment]
More details, it looks like the _cython extension did not build for your instance. Are you using the default startup script that is set by the deployment wizard?

**Comment by umairidris** [comment]
cc @dufton who setup our forseti instance: can you provide the info?

**Comment by dufton** [comment]
We deployed the instance using the setup script, I believe back in April. The startup script in the server VM is up to date with the latest dev version though.

**Comment by ahoying** [comment]
Please try this on the VM:

sudo su -
cd /home/ubuntu/forseti-security
pip install -U pip==9.0.3
pip install -U --upgrade-strategy eager --force-reinstall -r requirements.txt
reboot

I'm hopeful that fixes the weird grpc install issue.

**Comment by ahoying** [comment]
Closing as there has been no additional follow up.
