### ISSUE TITLE
Fix the commit history between forsetisecurity.org-dev & forsetisecurity.org

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#2119]
The commit history diverged somehow between 2 branches and is creating some CLA problems every time we merge from forsetisecurity.org-dev to forsetisecurity.org.

**Comment by mirons-google** [comment]
I would just add that we also need to ensure there are no CLA issues every time either.

**Comment by joecheuk** [comment]
Description updated with CLA.

**Comment by jjawad-google** [comment]
joecheuk to investigate.

**Comment by joecheuk** [comment]
Since forsetisecurity.org-dev & forsetisecurity.org should be in sync, when we merge from dev -> non dev, we will need to use MERGE instead of SQUASH AND MERGE to avoid commit history conflicts. The website release steps have been updated to make it clear that only do MERGE.
