### ISSUE TITLE
Fix Flake8 styling issues in dev causing Travis build to fail

### ISSUE THREAD

**Issue by hshin-g** [GoogleCloudPlatform/forseti-security#2135]
Travis build is failing due to the many styling issues caught by Flake8. 

Will go through and fix each of the issues to remedy the problem.

@joecheuk @blueandgold

**Comment by hshin-g** [comment]
Majority of issues are `W504` Line break after binary operator.
Once you change so that the line break is before the binary operator, get `W503` Line break before binary operator.

Need to change the config file or settings so that it is aligned on only one.

**Comment by kevensen** [comment]
FWIW, I'm seeing this too.

**Comment by hshin-g** [comment]
PR created and merged into dev to address issue.
