### ISSUE TITLE
Wildcard behaviour is unconventional

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2189]
In Forseti rules the wildcard means "1 or more" whereas in Linux and other systems, it means "0 or more" [1]. This inconsistency causes surprising behaviour and can mislead customers. For example, today we are advertising blocking all europe locations by doing 'eu*' in the location rules, but this does not actually block "eu" itself!

Please consider changing the behaviour of * to be 0 or more.

[1]
```
$ echo "" > foo
$ ls
foo
$ ls f*
foo
$ ls foo*
foo
$ ls food*
ls: cannot access 'food*': No such file or directory
```

**Comment by umairidris** [comment]
Weirdly enough just * alone matches 0 or more, but * with a prefix requires there to be at least 1 character after the prefix...

```
if pattern_string == '*':
        return '^.*$'

return '^{}$'.format(re.escape(pattern_string).replace('\\*', '.+?'))
```

I also don't think we need the ? in the regex, it seems to be a no-op

**Comment by jjawad-google** [comment]
We will keep this in mind as we continue to design scanner 2.0.

**Comment by umairidris** [comment]
@jjawad-google do you think it's worth fixing the behaviour for all scanners sooner? The code change is trivial. I wonder how many people are misinterpreting what the wildcard does and misusing it. There is no documentation on this behaviour outside of looking at the code.

I coded a workaround specifically for the location scanner as being able to do us* is very important for the locations (match both locations US and US-WEST1), but others still remain.
