### ISSUE TITLE
cloudbuild.yaml Add a Unit Test Build Step

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2228]
Possibly add a unit test build step in cloudbuild.yaml
rough example:

- name: gcr.io/cloud-builders/docker
   args: ['run', 'gcr.io/$PROJECT_ID/forseti', '<_test command(s) to be determined_>' ]
   waitFor: ['forseti']
   id: unittest

**Comment by Red-Five** [comment]
This runs the unit tests in cloud build.

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - 'gcr.io/$PROJECT_ID/forseti'
  - 'python'
  - '-m'
  - 'unittest'
  - 'discover'
  - '--verbose'
  - '-s'
  - '.'
  - '-p'
  - '*_test.py'  
  waitFor: ['forseti']
  id: unittest

**Comment by jjawad-google** [comment]
@angelsungoogle will work with you to get this feature started in Forseti.

**Comment by angelsungoogle** [comment]
@Red-Five In our meeting this Friday, lets also touch base on this issue, along with #2227, #2237, #2162, and #2084 ;)

**Comment by Red-Five** [comment]
unit test step is here: https://github.com/GoogleCloudPlatform/forseti-security/pull/2283

**Comment by angelsungoogle** [comment]
proposed change: #2335
