### ISSUE TITLE
No forseti.service present after successfull deployment

### ISSUE THREAD

**Issue by lmgcp** [GoogleCloudPlatform/forseti-security#2232]
First, help us help you by providing the following information when opening an issue.

 - Version: 2.7.0
 - Modules: All since there is no forseti.service even after successfull deployment.
 - When running commands to reload or check the status on server VM
command: sudo systemctl restart forseti.service
Output: Failed to restart forseti.service: Unit forseti.service not found.

command: sudo systemctl status forseti.service
Output:Unit forseti.service could not be found.

![image](https://user-images.githubusercontent.com/44876659/48218588-3653a200-e3b0-11e8-9a2d-5379e2af8918.png)

command: tail -f /var/log/forseti.log

![image](https://user-images.githubusercontent.com/44876659/48218295-93028d00-e3af-11e8-943b-c8c21176075d.png)

 - Deployed forseti via installer but with an non- Organizational admin/project-owner account.
- All the required services were successfully created by forseti
- Server and Client VM's are successfully created.

Thanks!

**Comment by lmgcp** [comment]
Is there any update or troubleshooting steps?

**Comment by joecheuk** [comment]
Hi @lmgcp ,

There was an issue with 2.7.0, we have patched the problem. Do you mind doing another fresh installation and see if that helps?

Thanks,
Joe

**Comment by jjawad-google** [comment]
#2193

**Comment by lmgcp** [comment]
This can be closed as i had to restart the server VM to fix it.

**Comment by joecheuk** [comment]
Thanks for the updates! @lmgcp
