### ISSUE TITLE
Notifier failing to send to gcs and emails

### ISSUE THREAD

**Issue by ajayakumar1983** [GoogleCloudPlatform/forseti-security#2246]
We see the sendgrid api quota might be issue with email notification but it also don't sent notification to GCS bucket. is there a dependency with sendgrid api ?

Logs:

[forseti-security][2.7.0] google.cloud.forseti.services.notifier.service(_run_notifier): Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/services/notifier/service.py", line 104, in _run_notifier self.service_config) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/notifier/notifier.py", line 151, in run notifier.run() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/notifier/notifiers/email_violations.py", line 179, in run self._send(notification=email_notification) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/notifier/notifiers/email_violations.py", line 171, in _send attachment=attachment) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/common/util/email.py", line 123, in send response = self._execute_send(email) File "build/bdist.linux-x86_64/egg/retrying.py", line 49, in wrapped_f return Retrying(*dargs, **dkw).call(f, *args, **kw) File "build/bdist.linux-x86_64/egg/retrying.py", line 206, in call return attempt.get(self._wrap_exception) File "build/bdist.linux-x86_64/egg/retrying.py", line 247, in get six.reraise(self.value[0], self.value[1], self.value[2]) File "build/bdist.linux-x86_64/egg/retrying.py", line 200, in call attempt = Attempt(fn(*args, **kwargs), attempt_number, False) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/common/util/email.py", line 65, in _execute_send return self.sendgrid.client.mail.send.post(request_body=email.get()) File "build/bdist.linux-x86_64/egg/python_http_client/client.py", line 252, in http_request return Response(self._make_request(opener, request, timeout=timeout)) File "build/bdist.linux-x86_64/egg/python_http_client/client.py", line 176, in _make_request raise exc ForbiddenError

**Comment by red2k18** [comment]
@ajayakumar1983 There is no dependency with sendgrid api. Email notification will be sent when you provide the email configuration and you'll see violations in GCS bucket when you provide gcs_path and other details. Either way you need to set the 'should_notify' field to 'true'. Please ensure the gcs_path you provided is correct. Let me know if the issue persists.
