### ISSUE TITLE
Update scanner online doc, log type, replace AUDIT_READ by ADMIN_READ

### ISSUE THREAD

**Issue by BrunoReboul** [GoogleCloudPlatform/forseti-security#2267]
On line document page [Defining Rules](https://forsetisecurity.org/docs/latest/configure/scanner/rules.html)
Section Cloud Audit Logging rules
Setting log_types
Valide value shows AUDIT_READ

Ask: replace AUDIT_READ by ADMIN_READ

The audit_logging_rules.yaml is OK
Reference doc: [Resource Manager Audit Logging Information](https://cloud.google.com/resource-manager/docs/audit-logging)
Thanks

**Comment by jjawad-google** [comment]
@joecheuk to investigate further.

**Comment by joecheuk** [comment]
Documentation updated, will be included in the next release.
