### ISSUE TITLE
Forseti firewall_rule.yaml issues

### ISSUE THREAD

**Issue by jgearheart** [GoogleCloudPlatform/forseti-security#2269]
Hello - I'm new to forseti and having issues getting basic firewall rules to match. for example. I'm simply trying to send a notification if the following policy exists:

Firewall rule in GCP
{
  "allowed": [
    {
      "IPProtocol": "tcp",
      "ports": [
        "22"
      ]
    }
  ],
  "creationTimestamp": "2018-11-16T11:30:16.216-08:00",
  "description": "safdsf",
  "direction": "INGRESS",
  "disabled": false,
  "enableLogging": false,
  "id": "xxxxx",
  "kind": "compute#firewall",
  "name": "adsf",
  "network": "projects/jg-build1/global/networks/default",
  "priority": 1000,
  "selfLink": "projects/jg-build1/global/firewalls/adsf",
  "sourceRanges": [
    "1.1.1.1/32"
  ]
}

my rule in firewall_rules.yaml:
- rule_id: 'golden_policy'
    description: Instances with internal tag must have a specific policy
    mode: matches
    match_policies:
      - name: 'firewall1'
        network: 'default'
        direction: ingress
        targetTags: 'internal'
        allowed:
          - IPProtocol: 'TCP'
            ports:
              - '22'
        sourceRanges:
        - '0.0.0.0/0'

Once the gcp policy was configured along with the rule in firewall_rules.yaml (edited /home/ubuntu/forseti-security/rules/firewall_rules.yaml, I ran the following commands to pull a new inventory, create a new model, run the scanner, and then run the notifier:
forseti inventory create --import_as testinv004
forseti model use testinv004
forseti scanner run
forseti notifier run

I've tried several other example policies but have been unsuccessful getting them to trigger a violation. I'm currently running the latest version 2.7.0. Any help would be sincerely appreciated.

**Comment by jjawad-google** [comment]
@hshin-g will follow up with you to help with configuration.

**Comment by hshin-g** [comment]
@jgearheart Are you still experiencing issues with this?

**Comment by jjawad-google** [comment]
Hi @jgearheart, are you still seeing this issue? If you are, please follow up on our slack channel: https://forsetisecurity.slack.com and we'll be able to provide you with more immediate support.
