### ISSUE TITLE
Is it safe to open 0.0.0.0/0 ingress for ssh?

### ISSUE THREAD

**Issue by pratikmallya** [GoogleCloudPlatform/forseti-security#2271]
Looking at https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/gcp/installer/forseti_server_installer.py#L146-L157

Is it good practice, security wise, to open a vm to traffic from everywhere?

**Comment by jjawad-google** [comment]
We will look into the best practice here.

**Comment by red2k18** [comment]
Admin proxy is a better way to manage and control ssh access to the VM and we will switch to admin proxy once it launches. Until then the firewall rule which allows external traffic on tcp:22 will stay. 

Thanks for bringing this up!

**Comment by pratikmallya** [comment]
What is admin proxy?
