### ISSUE TITLE
base dockerfile Google Cloud SDK installation bug

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2284]
Current code
Install the CloudSDK for `gcloud`.
RUN curl -sSL https://sdk.cloud.google.com 1> /dev/null | bash

This redirects curl to/dev/null which discards all input. As a result Google Cloud SDK is not installed.

Proposed fix.
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin

**Comment by jjawad-google** [comment]
@angelsungoogle to follow up.

**Comment by Red-Five** [comment]
Pull request for fix: https://github.com/GoogleCloudPlatform/forseti-security/pull/2296

**Comment by angelsungoogle** [comment]
proposed change: #2335
