### ISSUE TITLE
Add a Forseti Server Docker ENTRYPOINT Script

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2285]
Add a script to start Forseti server in Docker and reference it in the Forseti dockerfile
Rough solution

Download config files
(This requires fix for https://github.com/GoogleCloudPlatform/forseti-security/issues/2284 )
gsutil cp ${BUCKET}/forseti_conf_server.yaml /forseti-security/configs/forseti_conf_server.yaml
gsutil cp -r ${BUCKET}/rules /forseti-security/

TODO Error handling for gsutil cp

Start Forseti server
This requires the cloud sql proxy (side car) container is already running on 127.0.0.1:3306
forseti_server \
--endpoint "localhost:50051" \
--forseti_db "mysql://root@127.0.0.1:3306/forseti_security" \
--services scanner model inventory explain notifier \
--config_file_path "/forseti-security/configs/forseti_conf_server.yaml" \
--log_level=info \
--enable_console_log &

**Comment by Red-Five** [comment]
Before running above in Container Optimized VM (not GKE)

docker pull gcr.io/cloudsql-docker/gce-proxy:1.12

Start Cloud SQL Proxy
CLOUD_SQL_CONNECTION_NAME="<_project_>:<_region_>:<_cloud sql db_>"

sudo docker run -d -v /mnt/stateful_partition/cloudsql:/cloudsql \
-p 127.0.0.1:3306:3306 \
gcr.io/cloudsql-docker/gce-proxy:1.12 /cloud_sql_proxy \
-instances=${CLOUD_SQL_CONNECTION_NAME}=tcp:0.0.0.0:3306

**Comment by jjawad-google** [comment]
angelsungoogle@ will follow up.

**Comment by Red-Five** [comment]
Initial draft: https://github.com/GoogleCloudPlatform/forseti-security/pull/2297

**Comment by angelsungoogle** [comment]
#2335
