### ISSUE TITLE
[2-8-0]-90% of ressources are missing in the inventory

### ISSUE THREAD

**Issue by antoine-castex** [GoogleCloudPlatform/forseti-security#2292]
Since 2-8-0 inventory takes 5min (30min before)
got only 60 project ( 1250 before) and same for all ressources, violations .....

permissions seems ok, the service account is ok , i have add project viewer on organization level + org admin viewer to test = > same result ...

any idea ?

**Comment by antoine-castex** [comment]
i only see error from CAI during the inventory on cloud logging , this is my problem ?


[forseti-security][2.8.0] google.cloud.forseti.services.inventory.storage(populate_cai_data): Error populating CAI data: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: u'INSERT INTO cai_temporary_store (name, parent_name, content_type, asset_type, asset_data) VALUES (%s, %s, %s, %s, %s)'] [parameters: ((u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180923', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11603 characters truncated) ... \x0f\x1a\r1537657323469\nq\n\x02id\x12k\x1aifr-imt-isteau-datadesk-demo:00000_monitoring_france_private.appengine_googleapis_com_request_log_20180923'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180924', Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 754, in populate_cai_data commit_buffer.add(row) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 680, in add self.flush() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 686, in flush self.session.flush() File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2313, in flush self._flush(objects) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2440, in _flush transaction.rollback(_capture_exception=True) File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 66, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2404, in _flush flush_context.execute() File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 398, in execute rec.execute(self) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 563, in execute uow File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 181, in save_obj mapper, table, insert) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 836, in _emit_insert_statements execute(statement, multiparams) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 948, in execute return meth(self, multiparams, params) File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement compiled_sql, distilled_params File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1200, in _execute_context context) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception exc_info File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 265, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1170, in _execute_context context) File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/mysql/mysqldb.py", line 129, in do_executemany rowcount = cursor.executemany(statement, parameters) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 262, in executemany r = self._query('\n'.join([query[:p], ',\n'.join(q), query[e:]])) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 354, in _query rowcount = self._do_query(q) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 318, in _do_query db.query(q) OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: u'INSERT INTO cai_temporary_store (name, parent_name, content_type, asset_type, asset_data) VALUES (%s, %s, %s, %s, %s)'] [parameters: ((u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180923', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11603 characters truncated) ... \x0f\x1a\r1537657323469\nq\n\x02id\x12k\x1aifr-imt-isteau-datadesk-demo:00000_monitoring_france_private.appengine_googleapis_com_request_log_20180923'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180924', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11603 characters truncated) ... -appengine_googleapis_com_request_log_20180924\n\x1f\n\x0ccreationTime\x12\x0f\x1a\r1537742910547\n#\n\x10lastModifiedTime\x12\x0f\x1a\r1537742910547'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180925', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11603 characters truncated) ... \x0f\x1a\r1537829320034\nq\n\x02id\x12k\x1aifr-imt-isteau-datadesk-demo:00000_monitoring_france_private.appengine_googleapis_com_request_log_20180925'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180926', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11730 characters truncated) ... -appengine_googleapis_com_request_log_20180926\n\x1f\n\x0ccreationTime\x12\x0f\x1a\r1537916077561\n#\n\x10lastModifiedTime\x12\x0f\x1a\r1537937689699'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180927', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11730 characters truncated) ... \x0f\x1a\r1538002187086\nq\n\x02id\x12k\x1aifr-imt-isteau-datadesk-demo:00000_monitoring_france_private.appengine_googleapis_com_request_log_20180927'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180928', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11730 characters truncated) ... \x1a\x0esourceLocation\nB*@\n\x13\n\x04type\x12\x0b\x1a\tTYPE_BOOL\n\x11\n\x0bdescription\x12\x02\x1a\x00\n\x16\n\x04name\x12\x0e\x1a\x0ctraceSampled'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180929', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018092 ... (11730 characters truncated) ... -appengine_googleapis_com_request_log_20180929\n\x1f\n\x0ccreationTime\x12\x0f\x1a\r1538175233922\n#\n\x10lastModifiedTime\x12\x0f\x1a\r1538175233922'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_20180930', u'//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private', 'resource', u'google.bigquery.Table', '\n\x8c\x01//bigquery.googleapis.com/projects/55056767362/datasets/00000_monitoring_france_private/tables/appengine_googleapis_com_request_log_2018093 ... (11730 characters truncated) ... ring_france_private\n*\n\tprojectId\x12\x1d\x1a\x1bfr-imt-isteau-datadesk-demo\n:\n\x07tableId\x12/\x1a-appengine_googleapis_com_request_log_20180930') ... displaying 10 of 1024 total bound parameter sets ... (u'//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs/tables/cloudaudit_googleapis_com_data_access_20180629', u'//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs', 'resource', u'google.bigquery.Table', '\n{//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs/tables/cloudaudit_googleapis_com_data_access_20180629\x12\x15google.bigquery ... (122530 characters truncated) ... tModifiedTime\x12\x0f\x1a\r1530226330941\n`\n\x02id\x12Z\x1aXfr-imt-isteau-datadesk-demo:datadesk_logs.cloudaudit_googleapis_com_data_access_20180629'), (u'//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs/tables/cloudaudit_googleapis_com_data_access_20180630', u'//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs', 'resource', u'google.bigquery.Table', '\n{//bigquery.googleapis.com/projects/55056767362/datasets/datadesk_logs/tables/cloudaudit_googleapis_com_data_access_20180630\x12\x15google.bigquery ... (122530 characters truncated) ... tModifiedTime\x12\x0f\x1a\r1530312529628\n`\n\x02id\x12Z\x1aXfr-imt-isteau-datadesk-demo:datadesk_logs.cloudaudit_googleapis_com_data_access_20180630'))] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by jjawad-google** [comment]
We need to  root cause this error. hshin-g@ will follow up.  Might be cause of #2293.
