### ISSUE TITLE
Blacklist scanner crashes if no network interfaces found

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2294]
> [forseti-security][2.7.0] google.cloud.forseti.scanner.scanners.blacklist_scanner(get_instance_networks_interfaces): No VM network interfaces found. Exiting.
> [forseti-security][2.7.0] google.cloud.forseti.scanner.scanner(run): Error running scanner: BlacklistScanner Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 111, in run scanner.run() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/scanner/scanners/blacklist_scanner.py", line 144, in run self._find_violations(instances_network_interface_data)) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/scanner/scanners/blacklist_scanner.py", line 137, in _find_violations all_violations.extend(violations) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.7.0-py2.7.egg/google/cloud/forseti/scanner/audit/blacklist_rules_engine.py", line 216, in find_violations for network_interface in instance_network_interface: TypeError: 'NoneType' object is not iterable

The _retrieve code in the rule generator is hitting this line:

```
        if not network_interfaces:
            LOGGER.warn('No VM network interfaces found. Exiting.')
            return None, 0
```

I think just making this return [], 0 should work? Though I haven't dug through the rule generator code to see what would happen in this case.

**Comment by jjawad-google** [comment]
Might be related to : #1918
