### ISSUE TITLE
Add a .dockerignore File

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2303]
Ref. https://docs.docker.com/engine/reference/builder/#dockerignore-file

As we progress to running Forseti on Docker, we may wish to consider a .dockerignore file to exclude unnecessary files from the image.

**Comment by Red-Five** [comment]
https://github.com/GoogleCloudPlatform/forseti-security/pull/2344

**Comment by jjawad-google** [comment]
@angelsungoogle will follow up here.

**Comment by angelsungoogle** [comment]
#2335
