### ISSUE TITLE
Update IAM Explain to expand project(Viewer|Editor|Owner) iam bindings to the correct members.

### ISSUE THREAD

**Issue by ahoying** [GoogleCloudPlatform/forseti-security#2343]
Current IAM explain does not expand out the special IAM member types used by the legacy GCS bucket and bigquery policies to the real set of members represented by those bindings.

For example: projectEditor:test-project should expand out to all the members who have the roles/editor role on the test-project project IAM binding. The same for projectViewer and projectOwner bindings, for their respective roles.

**Comment by jjawad-google** [comment]
We will prioritize this as part of our planning efforts.
