### ISSUE TITLE
location scanner eu* 

### ISSUE THREAD

**Issue by BrunoReboul** [GoogleCloudPlatform/forseti-security#2350]
v2.8.0

### Current document indicates:
"Due to differences in region (europe-west1) vs multi regional (EU) naming, we recommend writing rules that can cover both (e.g. eu* instead of europe*)"
https://forsetisecurity.org/docs/latest/configure/scanner/rules.html#location-rules
https://github.com/GoogleCloudPlatform/forseti-security/blob/v2.8.0/rules/location_rules.yaml

### Issue
When testing with eu* as proposed in the doc, there is still violations on EU locations

### Workaround:
Whitelist 'eu*' and 'eu'

### Ask
Would it be possible to fix the code so it works as documented or to document the workaround?

**Comment by umairidris** [comment]
A workaround was coded in #2203 and which will be going into the next release.

**Comment by umairidris** [comment]
Note this was due to #2189.
