### ISSUE TITLE
Issue with connecting cloud SQL after password change

### ISSUE THREAD

**Issue by sparthe123** [GoogleCloudPlatform/forseti-security#2363]
I tried change the cloud SQL password, now forseti tool have issue to connect to cloudsql. Can someone help me to find the config file to update the new password. 

Getting below error
Access denied for user 'root'@'cloudsqlproxy' (using password: NO)

Finally, be sure to see the [FAQ](https://forsetisecurity.org/docs/latest/faq/) and [Get Help](https://forsetisecurity.org/docs/latest/develop/get-help.html) for assistance.

Thanks!

**Comment by joecheuk** [comment]
Hi @sparthe123 ,

We have added the instructions on how to connect forseti to cloud sql users with password and will be part of the faq on the forseti website in the next release. In the mean time, can you try out the instructions listed here and see if that works?

https://github.com/GoogleCloudPlatform/forseti-security/blob/51d6f329e16e9b27c68c56bac14a6d664a01106f/_faq/using_forseti/configure_db_password.md

Thanks,
Joe

**Comment by sparthe123** [comment]
Thanks , this helped

**Comment by joecheuk** [comment]
No problem - I will go ahead and close this issue for now, feel free to re-open if you have any more questions!
