### ISSUE TITLE
Add project_id to Big Query Resources

### ISSUE THREAD

**Issue by hshin-g** [GoogleCloudPlatform/forseti-security#2392]
Asset name change for bigquery resources- the project number in the name will be switched to project id: https://groups.google.com/a/google.com/forum/#!topic/cai-announcement/KTsupo3Z2Ik

Need to add in project_id in addition to the already existing project_number to accommodate.

**Comment by jjawad-google** [comment]
@hshin-g to link PR / close.

**Comment by hshin-g** [comment]
Merged in to release v2.9.0: #2393
