### ISSUE TITLE
Findings Sent to Cloud SCC Should Use the Update Method.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2443]
Findings are currently sent to Cloud SCC using the [`CreateFinding` method](https://github.com/GoogleCloudPlatform/forseti-security/blob/075821ebe7ff8cb7fafa90b7b83cdf0bdd3843a3/google/cloud/forseti/common/gcp_api/securitycenter.py#L124-L148).

Cloud SCC team has suggested that we change to using the `UpdateFinding` method, which also will create findings if they don't exist. Using `update` also has the benefit of modifying the finding.

**Comment by antoine-castex** [comment]
When a finding is sent to CSCC , and if this finding is fixed , when did he disapear from CSCC ?? because 2 weeks after and still here for me ...

**Comment by red2k18** [comment]
Hi @antoine-castex, thanks for bringing this up! Have you tried resolving the finding from the CSCC GUI itself?

**Comment by katze120** [comment]
I have the same issue with Forseti findings too, and am not able to find any way to close the findings from CSCC GUI. Only workaround I found so far is to add security marks to hide the findings by filtering. 
FYI - Findings from other sources e.g. Cloud Security Scanner will disappear from CSCC automatically if the finding is not there at subsequent scan; they also have "eventTime" updated if they persists.

**Comment by red2k18** [comment]
Thanks all for reporting this issue! Below is the solution I came up with. Please let me know your thoughts on this so we can fix this asap.

Create an update method in Forseti that will compare the results of the latest notifier run with the results of the previous notifier run that is displayed on CSCC dashboard, and update the findings in CSCC accordingly. This will ensure the violations displayed in CSCC are consistent with the results of the latest notifier run.

@MartenvanWezel eager to hear your thoughts on this.

**Comment by red2k18** [comment]
Thanks Marten for your kind response! I will work on creating the implementation plan then.

**Comment by red2k18** [comment]
This issues is fixed in #2618 and is part of v2.13.0 that is slated for release this week.
