### ISSUE TITLE
503/500 from repeated members.list_next() calls

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#245]
The 503 is mentioned in #241.  I can repro it by repeated calls of the _retrieve(), too.  Addressed in PR #244 to increase the page result.  But there is a concern that the root cause might still be lurking, especially for super-large orgs.

Attempting to add trace token is not returning reports on the internal errors.  So, we need to keep investigating.  Potentially, determining what is the real rate limit that is safe to retrieve the group members.

![screenshot from 2017-04-26 08 19 54](https://cloud.githubusercontent.com/assets/6977544/25446050/111e3730-2a65-11e7-8e00-6f27dcd54092.png)

**Comment by ahoying** [comment]
Inventory redesigned in 2.0, can not reproduce. Closing issue.
