### ISSUE TITLE
Bad Link on Website Documentation for "Start Developing on Forseti"

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2453]
In https://forsetisecurity.org/docs/latest/develop/ page, the link for `Start Developing on Forseti` goes to the get help page.  The link on the left sidebar is correct.

![image](https://user-images.githubusercontent.com/6977544/50493641-b91dd400-09d3-11e9-8ecd-5b39c3ca2e8e.png)

**Comment by jjawad-google** [comment]
Update broken link to match sidebar link.
