### ISSUE TITLE
forseti inventory create fails: can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by rtoma** [GoogleCloudPlatform/forseti-security#2467]
Hi,

We are running Forseti 2.9.0 on a GCE VM using CloudSQL mysql as DB. Server and client are running on same VM. All manually deployed.

`forseti inventory create` fails on:
```
Jan  4 07:00:18 localhost forseti-cron: + forseti inventory create --import_as 20190104T060018
Jan  4 07:05:37 localhost forseti-cron: {
Jan  4 07:05:37 localhost forseti-cron:   "errors": 0,
Jan  4 07:05:37 localhost forseti-cron:   "warnings": 0,
Jan  4 07:05:37 localhost forseti-cron:   "step": "",
Jan  4 07:05:37 localhost forseti-cron:   "finalMessage": false,
Jan  4 07:05:37 localhost forseti-cron:   "lastError": "",
Jan  4 07:05:37 localhost forseti-cron:   "id": "1546581619066946",
Jan  4 07:05:37 localhost forseti-cron:   "lastWarning": ""
Jan  4 07:05:37 localhost forseti-cron: }
Jan  4 07:05:37 localhost forseti-cron: Error occurred on the server side, message: <_Rendezvous of RPC that terminated with:
Jan  4 07:05:37 localhost forseti-cron: #011status = StatusCode.UNKNOWN
Jan  4 07:05:37 localhost forseti-cron: #011details = "Exception iterating responses: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT cai_temporary_store.name AS cai_temporary_store_name, cai_temporary_store.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.content_type AS cai_temporary_store_content_type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, cai_temporary_store.asset_data AS cai_temporary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_store.content_type = %s AND cai_temporary_store.asset_type = %s AND cai_temporary_store.name = %s'] [parameters: [{}]]"
Jan  4 07:05:37 localhost forseti-cron: #011debug_error_string = "{"created":"@1546581937.855659016","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"Exception iterating responses: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT cai_temporary_store.name AS cai_temporary_store_name, cai_temporary_store.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.content_type AS cai_temporary_store_content_type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, cai_temporary_store.asset_data AS cai_temporary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_store.content_type = %s AND cai_temporary_store.asset_type = %s AND cai_temporary_store.name = %s'] [parameters: [{}]]","grpc_status":2}"
```

When I `systemctl restart forseti` it works. Until a few runs later. I can not find anything in the server logging worth mentioning.

---

First, help us help you by providing the following information when opening an issue.

 - [x] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
 - [x] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [x] Include errors, log output, and host operating system, including installed packages.
 - [x] Note how you deployed (via Deployment Manager, local system, etc.).

Secondly, if the issue is a feature request, be descriptive regarding what needs to be changed and why.

Finally, be sure to see the [FAQ](https://forsetisecurity.org/docs/latest/faq/) and [Get Help](https://forsetisecurity.org/docs/latest/develop/get-help.html) for assistance.

Thanks!

**Comment by jjawad-google** [comment]
@rtoma thank you for reporting this issue. We will route this to @ahoying to investigate.

**Comment by sparthe123** [comment]
I'm also having the same issue, any update on this, 



  "errors": 0, 
  "warnings": 0, 
  "step": "", 
  "finalMessage": false, 
  "lastError": "", 
  "id": "1547459862699122", 
  "lastWarning": ""
}
Error occurred on the server side, message: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invali
d transaction is rolled back [SQL: u'SELECT cai_temporary_store.name AS cai_temporary_store_name, cai_temporary_sto
re.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.content_type AS cai_temporary_store_content_
type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, cai_temporary_store.asset_data AS cai_tempo
rary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_store.content_type = %s AND cai_temporary_st
ore.asset_type = %s AND cai_temporary_store.name = %s'] [parameters: [{}]]"
        debug_error_string = "{"created":"@1547459899.401809471","description":"Error received from peer","file":"s
rc/core/lib/surface/call.cc","file_line":1036,"grpc_message":"Exception iterating responses: (sqlalchemy.exc.Invali
dRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT cai_temporary_store.name AS 
cai_temporary_store_name, cai_temporary_store.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.c
ontent_type AS cai_temporary_store_content_type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, 
cai_temporary_store.asset_data AS cai_temporary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_s
tore.content_type = %s AND cai_temporary_store.asset_type = %s AND cai_temporary_store.name = %s'] [parameters: [{}
]]","grpc_status":2}"

**Comment by jf-marquis-Adeo** [comment]
hello, i has the same issue until i upgrade the sql database to 2 CPU instead of 1.

**Comment by joecheuk** [comment]
Hi @jf-marquis-Adeo , we have added session rollback when importing the CAI data and we are not able to reproduce this issue on our end. I will go ahead and close the issue for now, if you experience the same problem in the latest version, feel free to re-open this issue.
