### ISSUE TITLE
Notifier failure

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2476]
> [forseti-security][2.9.0] google.cloud.forseti.services.notifier.service(_run_notifier): 'NoneType' object has no attribute 'replace' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/services/notifier/service.py", line 123, in _run_notifier self.service_config) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/notifier/notifier.py", line 189, in run InventorySummary(service_config, inventory_index_id).run() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py", line 264, in run details_data = self._get_details_data() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py", line 229, in _get_details_data details = inventory_index.get_details(session) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 282, in get_details resource_details = details_function(session, resource) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 186, in get_lifecycle_state_details new_key = key.replace('\"', '').replace('_', ' ') AttributeError: 'NoneType' object has no attribute 'replace'

Running from a fresh Forseti install from dev branch (today).

**Comment by umairidris** [comment]
Output from forseti client:

> 
> $ forseti notifier run
> {
>   "serverMessage": "Resource 'iam_policy_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'audit_logging_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'blacklist_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'bigquery_acl_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'buckets_acl_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'cloudsql_acl_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'enabled_apis_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'firewall_rule_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'forwarding_rule_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'ke_version_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'ke_violations' has no violations"
> }
> {
>   "serverMessage": "Resource 'groups_violations' has no violations"
> }
> {
>

**Comment by blueandgold** [comment]
@umairidris This should be fixed by PR #2450, and part of the 2.10 release.  Can you please try that?  If you still have issues, please reopen this issue.  Thanks!
