### ISSUE TITLE
Support Forseti to Crawl a Subset of an Organization (i.e. multiple folders)

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2479]
Per user request:
- install Forseti in Project AA under Folder A
- crawl folders/projects/resources in other Folders B,C,D

**Comment by jjawad-google** [comment]
Assigned to @ahoying to develop an implementation plan.

**Comment by umairidris** [comment]
Could also solve #2471. Would be great if we can use it to add/remove projects as well.
