### ISSUE TITLE
Fix error caused by removing content from `global` section in config file

### ISSUE THREAD

**Issue by red2k18** [GoogleCloudPlatform/forseti-security#2486]
Workaround was to add a placeholder as shown below.
```
global:

    dummy_key: this_is_just_a_placeholder
```

![global_config_error](https://user-images.githubusercontent.com/41486977/51000498-2eb09680-14e2-11e9-8e82-70ee2d6aa1f3.png)

**Comment by jjawad-google** [comment]
Fixed in #2487.
