### ISSUE TITLE
Below error is displayed when project/folder is set as root instead of org.

### ISSUE THREAD

**Issue by red2k18** [GoogleCloudPlatform/forseti-security#2494]
`ApiExecutionError: GCP API Error: unable to get organizations/XXXXXXXXX from GCP:`

**Comment by jjawad-google** [comment]
Hi @red2k18 could you provide us with more context around this error: what exactly did the user do to arrive at this error condition?

**Comment by red2k18** [comment]
When the root is set as `project`, permissions for the `organization` are fetched. This scenario throws this error which is non-fatal but misleading. Ideally the permissions for the `organization` should not be fetched if Forseti is running on a `project` or `folder`.

**Comment by ahoying** [comment]
Related to #2479, this extra log message should be fixed by the new code to resolve that issue.

**Comment by red2k18** [comment]
Great, thanks Andrew! Closing this issue then.
