### ISSUE TITLE
Location Scanner not updating users with violations in the following scenarios

### ISSUE THREAD

**Issue by red2k18** [GoogleCloudPlatform/forseti-security#2509]
1. Buckets created in `Multi-Regional`.
2. When scanner is  run on a `project` instead of `organization`.

Violations were not found in `violations` table as well.

**Comment by blueandgold** [comment]
As mentioned on slack (screenshot below), `Project ID` should be used, not `Project Number`.  I have verified that this is working as intended.

![image](https://user-images.githubusercontent.com/6977544/51758100-c92fde80-2079-11e9-920c-1021a8b260db.png)
