### ISSUE TITLE
gcp_install.py fails when running on virtualenv with --no-cloudshell

### ISSUE THREAD

**Issue by maurofaccenda** [GoogleCloudPlatform/forseti-security#2512]
Forseti Version: 2.10.0
Module: installer (install/gcp_installer.py)
Error message:
```
$ python install/gcp_installer.py --type=server
Command "pip install ruamel.yaml --user" failed/timeout, retrying...
Command "pip install ruamel.yaml --user" failed/timeout, retrying...
Command "pip install ruamel.yaml --user" failed/timeout, retrying...
Command "pip install ruamel.yaml --user" failed/timeout, retrying...
Command "pip install ruamel.yaml --user" failed/timeout, retrying...
Error installing package ruamel.yaml
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
OS: Manjaro Linux
Python Version: 2.7 (from virtualenv)

When running gcp_install.py from my own system (not a cloud shell) it tries to install some pip packages by running `pip install <package> --user`, which does not work when running from a virtualenv, generally, on virtualenv you don't really need to specify `--user`.

Suggestions:
1. add all required packages to requirements.txt so the user can install the way they prefer (eg: `pip install -r requirements --user`). The code could also check for them and automatically try to install.
2. check if the current python env is running on a virtualenv (here is an elegant way of doing it: https://stackoverflow.com/a/42580137) and only use the `--user` parameter if it is not an virtualenv.

**Comment by blueandgold** [comment]
Thank you for reporting this.  But due to the many possible environments, we had to pick 1 environment to support, and that would that is the cloud shell.  And that is why the installer has `gcp` in its name.  It's only job is to deploy Forseti onto GCP.

When we install virtual environment, it is usually for setting up our dev environment.  Is that what you are aiming to do here?  You can follow our [dev setup guide](https://forsetisecurity.org/docs/latest/develop/dev/setup.html) for setup in virtual environment.

**Comment by maurofaccenda** [comment]
Hi, thanks for your reply.

I am not sure if I understand your comment correctly, so let me try to add some more info.

I am trying to deploy Forseti on GCP, However, I'd like to be able to run the installer it from another environment (ex: my own laptop), so no Cloud Shell. As there is a parameter (`--no-cloudshell`) it makes me think this scenario is supported, also the documentation says it is "best to use Cloud Shell" and the only mentioned reason is that it ensures the latest Cloud SDK would be used. Again, that doesn't exclude the idea of being able to run it from my laptop, right?

Anyway, if the idea is to not support this scenario, please remove the parameter and update the documentation.

If the scenario is supported, then this would be a good improvement: allow running from virtualenvs.

Either way, I guess there is something to be done and the issue shouldn't be closed.

Once again, thanks for the answer.
