### ISSUE TITLE
Add documentation for EAP Scanner user fix #2527

### ISSUE THREAD

**Issue by hshin-g** [GoogleCloudPlatform/forseti-security#2546]
References PR #2527 

Need to add in documentation for users field in Forseti website here: https://forsetisecurity.org/docs/v2.9/configure/scanner/rules.html#external-project-access-rules

Should look like:

- name
  - Description: The name of the rule.
  - Valid values: String.
- allowed_ancestors
  - Description: The folder or organization that is allowed as an ancestor of a project.
  - Valid values: String, organizations/111 or folder/111.
- users
  - Description: Optional. The users that are allowed access. Omitting this section would mean that the rule applies to all users in the organization.
  - Valid values: String, user1@example.com.

**Comment by hshin-g** [comment]
@joecheuk @blueandgold Please take a look.

**Comment by kevensen** [comment]
@hshin-g @blueandgold I'm happy to update this documentation.  I chatted with @blueandgold yesterday about this.  

I think I am supposed to edit the docs in the "forsetisecurity.org-dev" branch.  However, I do not see the existing "External Project Access Scanner" documentation in that branch.

I do see it in the "forsetisecurity.org" branch.  Can you please clarify?
