### ISSUE TITLE
Remove protoc installation script from travis.yml once protoc >= 3.0 in travis supported ubuntu images

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#255]
Once yakkety is available on Travis CI we can remove the protoc installation script and just install the [protobuf-compiler package](http://packages.ubuntu.com/yakkety/protobuf-compiler).

**Comment by carise** [comment]
Is this still relevant ?

**Comment by mirons-google** [comment]
This is no longer relevant.
