### ISSUE TITLE
KMS Scanner should ignore states other than CryptoKeyVersionState.ENABLED

### ISSUE THREAD

**Issue by rgmenon** [GoogleCloudPlatform/forseti-security#2572]
First, help us help you by providing the following information when opening an issue.

 - [x] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
2.11.0

 - [x] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
KMS Scanner ('CRYPTO_KEY_VIOLATION')

 - [x] Include errors, log output, and host operating system, including installed packages.
 - [x] Note how you deployed (via Deployment Manager, local system, etc.).
Deployment Manage

The KMS key scanner is not ignoring CryptoKeyVersionState 'DESTROYED' and reports them in violations. This results in polluting real violations with false positives. Suggest that only:
state == CryptoKeyVersionState.ENABLED be scanned.

Hopefully this is a quick fix.

**Comment by rgmenon** [comment]
Adding link to documentation for all the states:
https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys.cryptoKeyVersions#CryptoKeyVersion.CryptoKeyVersionState

**Comment by red2k18** [comment]
#2573
