### ISSUE TITLE
[2.11.0 - 2.11.1 ] Wrong version number

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [GoogleCloudPlatform/forseti-security#2598]
hello
just a small bug in auto update
after reboot code is well upgrade to 2.11.1  in file google/cloud/forseti/scanner/audit/kms_rules_engine.py :
` state = key.primary_version.get('state')
if not state == 'ENABLED':
return violations`
but version number is not correct in log file 
`2019-02-26 05:50:06,645 INFO [forseti-security][2.11.0]`

**Comment by red2k18** [comment]
#2600
