### ISSUE TITLE
Helper function to merge paged results.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#263]
- [x] Create helper function
- [ ] Update code to use it

See the TODO in admin_directory.py  This should probably go in the _base_client.py

![image](https://cloud.githubusercontent.com/assets/6977544/25712539/c8812ef4-30a6-11e7-9989-02fc413dd68b.png)

**Comment by carise** [comment]
Is this still open? I saw the build_paged_results() method call being used, somewhere

**Comment by mirons-google** [comment]
The function has been created [here](https://github.com/GoogleCloudPlatform/forseti-security/blob/master/google/cloud/security/common/gcp_api/_base_client.py#L104). This issue should be re-written to go and implement it where it's needed.

**Comment by blueandgold** [comment]
Fixed by PR #335 and #337
