### ISSUE TITLE
CSCC / CAI Inventory Scan Question

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2658]
CAI updates inventory at least once a day.
(Though user initiated ad hoc scans can be done any time.)
Ref. https://cloud.google.com/security-command-center/docs/concepts-overview#assets_summary

Does Forseti trigger a CAI scan to refresh CAI inventory each time Forseti runs its inventory generation process?

**Comment by joecheuk** [comment]
Hi @Red-Five , the documentation you are referring to is for Cloud Security Command Center (the UI on GCP that also displays asset inventory information, they update at least once a day on their end), Forseti triggers a new CAI API call every time the inventory process is run so the data that we scan on is the most recent one from the CAI.

Feel free to reopen the issue if you have more questions!
