### ISSUE TITLE
User is unable to create or update CSCC findings.

### ISSUE THREAD

**Issue by red2k18** [GoogleCloudPlatform/forseti-security#2664]
Update List API parameters so user is able to create or update CSCC findings again.

**Comment by red2k18** [comment]
![image](https://user-images.githubusercontent.com/41486977/54898325-0bfb1080-4e89-11e9-8ebc-3561af4aa8ef.png)

**Comment by Red-Five** [comment]
Confirming this is a repeatable issue. I have just installed v 2.13 at a new client and we are seeing the exact same issue.

**Comment by red2k18** [comment]
@Red-Five, are you seeing findings on the CSCC dashboard?

**Comment by Red-Five** [comment]
No findings in CSCC.

**Comment by red2k18** [comment]
Perfect. Thanks for checking!

**Comment by red2k18** [comment]
@Red-Five A patch (v2.13.1) has been released that fixes this issue. Please reset the server VM for changes to take effect.

**Comment by red2k18** [comment]
#2667 fixes this issue.

**Comment by Red-Five** [comment]
Confirmed issue resolved for us. Many thanks.
