### ISSUE TITLE
Website Display Issue

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2712]
For last day or so seeing odd issue when first going to https://forsetisecurity.org on Chrome
After navigating to links on the page, the issue resolves.

![image](https://user-images.githubusercontent.com/25078066/55596696-c3501c80-56fe-11e9-8bb6-004d0b617880.png)

**Comment by Red-Five** [comment]
I am no longer able to reproduce this issue after making updates to my local PC including Chrome update.

I did clear cache and reproduce the issue before reporting it; however it may just have been an issue specific to my local setup.

**Comment by hshin-g** [comment]
Unable to reproduce issue. Closing.
