### ISSUE TITLE
Groups Settings Update Instructions Are Needed

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2721]
User report on slack:
The upgrade instructions for 2.14 need to mention the api scopes and api enablement for Groups Settings.

https://forsetisecurity.org/docs/latest/setup/upgrade.html

See the needed api scope here:
https://forsetisecurity.org/docs/latest/configure/inventory/gsuite.html#enable-the-service-account-in-your-g-suite-admin-control-panel

**Comment by joecheuk** [comment]
Resolved #2722
