### ISSUE TITLE
Inventory and Scanning should support bigquery datasets.

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#281]

**Comment by blueandgold** [comment]
Inventory is addressed by PR #277

**Comment by mirons-google** [comment]
@thenenadx as I believe your team volunteered to write the scanner for this data.

**Comment by thenenadx** [comment]
@mirons-google Yes, that's correct and I'm the one that volunteered to do it

**Comment by thenenadx** [comment]
Scanner is addressed in [#365](https://github.com/GoogleCloudPlatform/forseti-security/pull/365)

**Comment by carise** [comment]
I think we can close this issue now
