### ISSUE TITLE
bigquery inventory failing, missing project key in api response

### ISSUE THREAD

**Issue by bgres** [GoogleCloudPlatform/forseti-security#308]
I got an "TypeError: 'NoneType' object is not iterable" exception thrown in [bigquery.py:66](https://github.com/bgres/forseti-security/blob/master/google/cloud/security/common/gcp_api/bigquery.py#L66)
`for project in result.get('projects')`

When printing the variable `result` it looks like 
```
{u'totalItems': 0, u'kind': u'bigquery#projectList', u'etag': u'"..."'}
```
so it seems the key `projects` is not contained in the result for the API call bigquery_projects_api.list() [1] when the number of projects is 0 and a sanity check for that would be needed.

[1] https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list

**Comment by mirons-google** [comment]
Thanks for opening this issue. I'll work on a fix shortly.

**Comment by mirons-google** [comment]
@bgres this should be resolved now.
