### ISSUE TITLE
Ignore "Access not configured"

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#311]
<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/sample--project/aggregated/backendServices?alt=json returned "Access Not Configured. Compute Engine API has not been used in project 11 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute-component.googleapis.com/overview?project=11 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">

I haven't diagnosed why this is occurring in some projects in my test org, but we should handle these types of errors.

**Comment by mirons-google** [comment]
This is also happening on /forwardingRules

2017-05-30 16:15:45,271 google.cloud.security.inventory.pipelines.load_forwarding_rules_pipeline ERROR    _retrieve GCP API Error: unable to get forwarding_rules from GCP:
<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/sample--project/aggregated/forwardingRules?alt=json returned "Project 11 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute-component.googleapis.com/overview?project=11 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">

**Comment by mirons-google** [comment]
In my project where the service account exists these APIs are enabled:
- Google Compute Engine API
- Google Compute Engine Instance Group Manager API
- Google Compute Engine Instance Group Updater API
- Google Compute Engine Instance Groups API

**Comment by mirons-google** [comment]
@matthewg mind taking a look at this for us?

**Comment by carise** [comment]
Do the target projects have compute engine API enabled? I recall getting errors on the projects that don't have compute engine API enabled.

**Comment by mirons-google** [comment]
I don't know exactly and I don't have permissions necessarily to check each project.

Is the answer here different error handling for 403s instead of letting it raise?

**Comment by carise** [comment]
I think these kinds of errors (API not enabled) should just be ignored, but I don't think we can make any assumptions about 403s. We currently don't have a formal policy about pipeline errors, so we might want to wait on this until we decide what to do.

**Comment by mirons-google** [comment]
They're disconcerting for the average user as they're reported as errors on the console.

Arguably, each API should know which responses are harmless and should be ignored. They should be caught and checked. It might also be worth writing a row in that table for the run with a reason as to why it couldn't be retrieved.

**Comment by carise** [comment]
I've assigned @matthewg as I believe this issue is a much larger thing to tackle.

We should probably create an errors table for each snapshot and log all errors related to that snapshot. Probably the schema should have something like

```
project_id
reason
time_occurred
gcp_resource_id
```

**Comment by matthewg** [comment]
Sample response:
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Compute Engine API has not been used in project 428010280681 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute-component.googleapis.com/overview?project=428010280681 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/compute-component.googleapis.com/overview?project=428010280681",
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Compute Engine API has not been used in project 428010280681 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute-component.googleapis.com/overview?project=428010280681 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
}
​
I think that it'd make sense to just suppress these errors and return an empty list for the resource.  After all, if the Compute API isn't enabled on a project, we know that it has no Compute resources in it!

**Comment by carise** [comment]
Makes sense. It looks like we can figure out what to do for the error based on the error response object's reason.

**Comment by matthewg** [comment]
2d8e865 suppresses the "API not enabled" errors.  I'll make a PR for that as soon as #307 is merged.

**Comment by carise** [comment]
I think this issue has been resolved, so closing it
