### ISSUE TITLE
Issues loading backend services data into cloudsql

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#312]
I'm receiving the following errors on [dao.py:186](https://github.com/GoogleCloudPlatform/forseti-security/blob/master/google/cloud/security/common/data_access/dao.py#L186)

google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: 'False' for column 'enable_cdn' at row 1
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'affinity_cookie_ttl_sec' at row 2
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'enable_cdn' at row 2
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'port' at row 2
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'affinity_cookie_ttl_sec' at row 3
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'enable_cdn' at row 3
  cursor.execute(load_data_sql)
google/cloud/security/common/data_access/dao.py:186: Warning: Incorrect integer value: '' for column 'port' at row 3

**Comment by mirons-google** [comment]
@matthewg mind taking a look at this for us?

**Comment by matthewg** [comment]
Fixed by 483fbd9.
