### ISSUE TITLE
Add More Resource-specific IAM Policies to Inventory

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#334]
@felixbb metioned every asset type that can have an IAM policy will also expose them via getIAMPolicy() in the api.

https://cloud.google.com/s/results/?q=getIamPolicy&p=%2Fcompute%2Fdocs%2F

This is needed by explain to provide a full picture, with additional uses to scan for IAM based security compliance scanning.

Method: projects.serviceAccounts.getIamPolicy
Buckets: getIamPolicy
Method: projects.locations.keyRings.getIamPolicy
Method: projects.topics.getIamPolicy

**Comment by davidbernick** [comment]
This is very desired by me (platinum customer of GCP) and the Federal Government (platinum customer of planet earth).

**Comment by gbrindisi** [comment]
Hello! This is becoming a desired feature for us as well.

**Comment by mirons-google** [comment]
**Issue Review**:
These will be part of the FS2.0 release:
 * Method: projects.serviceAccounts.getIamPolicy
 * Buckets: getIamPolicy

These two are remaining:
 * Method: projects.locations.keyRings.getIamPolicy
 * Method: projects.topics.getIamPolicy

The core team interested in adding:
 * PubSub
 * Cloud KMS
 * Cloud Endpoints

@davidbernick @gbrindisi Any suggestions on others?

**Comment by mirons-google** [comment]
@blueandgold to update this

**Comment by jjawad-google** [comment]
We are currently and constantly adding all of the IAM policies as they are on-boarded from CAI.
