### ISSUE TITLE
Inventory loader should collect and store required data for the enforcer module

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#52]
This should include
* Firewall rules
* Network configuration(s)

**Comment by blueandgold** [comment]
Looking at the existing protos, these will be:
- firewalls
- networks
- subnetworks

**Comment by blueandgold** [comment]
First part of the firewall rule: #285 ; need to use the beta api to get additional fields.

**Comment by mirons-google** [comment]
@blueandgold Is this complete?

**Comment by blueandgold** [comment]
This is in-place in 2.0 inventory.
