### ISSUE TITLE
Create setup screencast(s)

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#528]
For now, just do a simple screencast of the wizard in action. Scrub all the sensitive data from the cast, as well.

**Comment by blueandgold** [comment]
Not sure if you want this to be part of the current focus on deployment, but please feel free to bump this down from P0.

**Comment by carise** [comment]
I've changed to P1 because I think while this is important, it is not exactly a showstopper, but it's definitely more than "nice to have". :)
