### ISSUE TITLE
Add local precommit checks for gh-pages instead of finding out on travis.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#539]
Travis is actually finding very useful broken links for documentation changes.  But these are not run as local precommit checks, but would save a lot of time.

**Comment by mirons-google** [comment]
Agreed. However, the complication of doing this requires local ruby binaries on the machine including jekyll and htmlproofer. Do we want to require these @blueandgold ? Their setup can be complicated especially with `rbenv` installations.

**Comment by blueandgold** [comment]
Wow, didn't know this is so involved.  If that's the case, then it's probably not worth to do the setup locally.  Resolving this issue, but please feel free to re-open it.
