### ISSUE TITLE
Allow passing of --no-launch-browser for gcp_setup installer

### ISSUE THREAD

**Issue by lukwam** [GoogleCloudPlatform/forseti-security#551]
When running the gcp_setup installer, there is no way to pass "--no-launch-browser". As a result, it can only be run on the local machine, because there is now way to paste the token into the client. 

It would be nice if there was a way to tell the installer not to launch a browser so i could pass --no-launch-browser to the gcloud auth login command that it calls.

**Comment by carise** [comment]
I am not opting to do this as part of #522, as it will be a requirement to pre-auth (either by running the installer in Cloud Shell or doing so manually).
