### ISSUE TITLE
gcp_setup instructions point to wrong link for gsuite setup

### ISSUE THREAD

**Issue by lukwam** [GoogleCloudPlatform/forseti-security#552]
After I completed the gcp_setup install, it showed me this in the output:
```
2) Follow instructions on how to link the service account to GSuite:

    http://forsetisecurity.org/docs/howto/gsuite-group-collection
```

but it appears that the actual link should be:

http://forsetisecurity.org/docs/howto/configure/gsuite-group-collection.html

**Comment by carise** [comment]
Argh, sorry about this. Thanks for reporting!

**Comment by carise** [comment]
bundled with #522
