### ISSUE TITLE
cloudresourcemanager v2beta1 should no longer be needed for folder functionality

### ISSUE THREAD

**Issue by lukwam** [GoogleCloudPlatform/forseti-security#556]
Folders are now GA, so it should no longer be necessary to use v2beta1 in order to get all the folder features.

`WARNING  __init__ API "cloudresourcemanager" version v2beta1 is not formally supported in Forseti, proceed at your own risk.`

You can get/set folder org polices in v1:

https://cloud.google.com/resource-manager/reference/rest/v1/folders

And all the get/set IAM policy stuff as well as create/delete/get/list/move/patch/search are all in v2:

https://cloud.google.com/resource-manager/reference/rest/v2/folders

**Comment by carise** [comment]
thanks, will take care of it when tackling #508

**Comment by carise** [comment]
closing as this is a duplicate of #508
