### ISSUE TITLE
Inventory should collect service account details

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#57]
* What keys are generated, exported
* Who has access to the account
* IAM permissions

**Comment by blueandgold** [comment]
Nenad's design proposal here:
https://docs.google.com/document/d/1YYiseiuw0l79j6ZELKcGBbMV749nX-8gf1z0blHb5kg/edit#

**Comment by blueandgold** [comment]
The inventory of service accounts are resolved by PR #541.

**Comment by blueandgold** [comment]
Related to issue #795

**Comment by mirons-google** [comment]
@blueandgold do you know what's left to do here?

**Comment by blueandgold** [comment]
The only explicit item left here is the IAM policy of the service accounts.  It's not put of the 2.0 release, but can do it afterwards.

**Comment by ahoying** [comment]
IAM Policies of service accounts are in the 2.0 crawler already, in PR #865. I'm closing this issue.
