### ISSUE TITLE
Inventory summary counts for IAM policies not accurate

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#575]
We are currently counting the number of rows in the IAM policies table, but we should be counting the number of rows in the raw IAM policies tables. (i.e. only one IAM policy per resource)

![screen shot 2017-08-21 at 3 06 25 pm](https://user-images.githubusercontent.com/14340/29540246-5895cd98-8682-11e7-9692-1e3fa54068dd.png)

For example, there was only 1 organization found during this data import, but Forseti reports that there are 207 org iam policies, when in fact there should only be 1 IAM policy for the org.

**Comment by arbeit** [comment]
Anyone working on this one? If no, I'd like to fix it.
