### ISSUE TITLE
Implement rule-set for security best practices in GCP

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#58]

**Comment by carise** [comment]
CIS
e.g. https://github.com/nccgroup/Scout2/blob/master/rulesets/cis-02-29-2016.json

**Comment by carise** [comment]
This will be started after we implement #432

**Comment by mirons-google** [comment]
@carise is taking over for me on this one, thanks!

**Comment by carise** [comment]
I'm going to close this because this should be an ongoing tenet to observe when creating new Forseti functionality.
