### ISSUE TITLE
Inventory & Scanner should support scanning + policies on Google Cloud Storage buckets

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#59]

**Comment by carise** [comment]
@thenenadx

**Comment by thenenadx** [comment]
Do we consider this done now? :)

**Comment by carise** [comment]
@blueandgold @mirons-google Ping to see if this issue should be closed

**Comment by blueandgold** [comment]
Indeed, it should!  Can you please attach Nenad's PRs to this, too?  Thanks!

**Comment by carise** [comment]
#240 #272
