### ISSUE TITLE
Clarify G Suite Groups setup documentation for different scenarios

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#613]
Currently if you use the setup wizard it creates a service account to use. The [docs](http://forsetisecurity.org/docs/howto/configure/gsuite-group-collection) say to create an account.

**Comment by carise** [comment]
2 cases

* G Suite setup partially done via setup wizard
* G Suite manual setup

**Comment by mirons-google** [comment]
@carise can you confirm this is fixed, if not please re-open.
