### ISSUE TITLE
group members inventory marked as success when groups failed

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#615]
Actual output:

Resource Name | Status | # in Snapshot
-- | -- | --
organizations | SUCCESS | 1
folders | SUCCESS | 12
folder_iam_policies | SUCCESS | 27
projects | SUCCESS | 100
appengine | SUCCESS | 31
backend_services | SUCCESS | 16
bigquery_datasets | SUCCESS | 0
buckets | SUCCESS | 74
buckets_acl | SUCCESS | 224
cloudsql | SUCCESS | 1
firewall_rules | SUCCESS | 434
forwarding_rules | SUCCESS | 65
instance_group_managers | SUCCESS | 25
instance_groups | SUCCESS | 41
instance_templates | SUCCESS | 34
instances | SUCCESS | 167
project_iam_policies | SUCCESS | 744
service_accounts | SUCCESS | 180
groups | FAILURE | Unknown
group_members | SUCCESS | Unknown
org_iam_policies | SUCCESS | 478

**Comment by mirons-google** [comment]
@blueandgold can you confirm if this is fixed?

**Comment by arbeit** [comment]
I would like to work on this if it is still outstanding and nobody else is doing it.

**Comment by blueandgold** [comment]
Thanks @arbeit , please take this!
