### ISSUE TITLE
Scanner email summary is confusing

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#617]
- It's unclear to me what we're trying to say in the `Resource Violations:` section.
- It found violations, but 0 errors?

Example summary:

`Forseti Security found some issues during the scan on 2017 Aug 31, 16:02:54 (UTC).

Resource Violations:
Organizations: 1 of 1

Errors: 0
See attached CSV for full violation details.

Organization | # Violations
-- | --
11111111111 | 42`

**Comment by carise** [comment]
Violations != errors.

An error is an actual problem with the scan e.g. couldn't scan all the data.
