### ISSUE TITLE
Installer should let the users know how often Forseti will run

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#618]
Right now there's no indication to me how often inventory,scanner, enforcer will run. It would be nice to let the user know the default times either or both in the docs and print statements.

**Comment by mirons-google** [comment]
@Tabrarian can we include this in our planned doc changes?

**Comment by Tabrarian** [comment]
Yes, this was something we noted as an issue on the "About" draft comments. Carise and I discussed adding documentation; ideally we'll note that at the end of the quickstart and then link over to configuration (http://forsetisecurity.org/docs/howto/configure/configuring-forseti) with details about how to change frequency specifically.
