### ISSUE TITLE
Improve and standardize all email notification summaries

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#635]
The current audit summary is incomplete (i.e. not all scanners send out a summary) and sends multiple emails. We should consolidate the notifications and include all summaries, in the very least.

related: #617, #616

**Comment by blueandgold** [comment]
Moving this to Auditor milestone, as this should be addressed by the Action Engine.

**Comment by jjawad-google** [comment]
Fixed in FS 2.0.
