### ISSUE TITLE
No TLS on forsetisecurity.org

### ISSUE THREAD

**Issue by daenney** [GoogleCloudPlatform/forseti-security#652]
Though perhaps not super critical it is slightly ironic that forsetisecurity.org itself is not available over TLS.

It seems to currently leverage GitHub Pages but there are ways of making TLS work in such scenario's. for example by leveraging Cloudflare: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc. The alternative would probably be to deploy this to AppEngine instead.

It's a small thing but it would be nice to have.

**Comment by mirons-google** [comment]
Thank you @daenney we share the same concerns. We will be looking into what we can do while still making the jekyll build easy and automatic.

**Comment by mirons-google** [comment]
This is resolved in #937
