### ISSUE TITLE
You do not have the necessary roles to grant roles that Forseti needs.

### ISSUE THREAD

**Issue by andrelss** [GoogleCloudPlatform/forseti-security#656]
**Hello, I am facing the following issue:**

+-------------------------------------------------------
|  Checking permissions
+-------------------------------------------------------
ERROR: (gcloud.organizations.get-iam-policy) You do not have permission to access organization [1734241926:getIamPolicy] (or it may not exist): The caller does not have permission

user@company.com is Org Admin? False
You do not have the necessary roles to grant roles that Forseti needs. Please have someone who is an Org Admin and either Project Editor or Project Owner for this project to run this setup. Exiting.

**That is weird because my user are "Project Owner", has anyone faced the same behavior? Thanks a lot.**

**Comment by carise** [comment]
Hi @andrelss, your user needs to be both Project Owner AND Organization Admin. Hope this helps!

**Comment by andrelss** [comment]
Hello Carise, thanks for the help.

Are you mean by the following? It still not working :(

![rights](https://user-images.githubusercontent.com/17025913/30593653-c38b64ae-9d21-11e7-84f6-fe16e39ba8ff.png)

**Comment by carise** [comment]
Hi @andrelss, I can't tell, but in your screenshot, are you Organization Administrator on the Project IAM policy or the Organization IAM policy? You need to be Organization Admin on the Organization IAM policy.

**Comment by andrelss** [comment]
I got it,!

I just realize that I am not Organization Admin :(

Thanks a lot for your help, I really appreciate.

**Comment by carise** [comment]
No problem! Sorry for the confusion! I'll file an issue to clarify in the installer and docs.
