### ISSUE TITLE
Is cloudsql-databases.py needed?

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#764]
```forseti-security/deployment-templates/cloudsql/cloudsql-databases.py``` does not seem to be used.

Instead, it is ```forseti-security/blob/dev/deployment-templates/cloudsql/cloudsql-database.py``` that seems to be used.

So, is there any need for ```cloudsql-databases.py```?  If not, can we remove it?

**Comment by carise** [comment]
probably can remove it, I don't remember why it's there.
