### ISSUE TITLE
Security: Domain wide delegation requires service account key to be available

### ISSUE THREAD

**Issue by felixbb** [GoogleCloudPlatform/forseti-security#775]
Due to lack of functionality within the google python client API, the service account key is required for the use of domain wide delegation against GSuite when enumerating users and groups.

The technical reason is the requirement for creating a signature as part of the authentication workflow. However, Cloud IAM offer signBlob API to perform signature operations. Hence it should be possible to implement the workflow without requiring the service account key to be available to the code but rather having the code run under the service account's authority in GCE.

This would improve security as Forseti/Explain would be working with a single service account as the ambient authority of the GCE instance.

**Comment by blueandgold** [comment]
Fixed by #1399 by changing to use the google.auth library.
