### ISSUE TITLE
Inventory support for IAM Custom Roles

### ISSUE THREAD

**Issue by marcin-kolda** [GoogleCloudPlatform/forseti-security#794]
Please add support for [IAM Custom Roles](https://cloud.google.com/iam/docs/understanding-custom-roles) in Inventory module. Custom roles can be defined on org or project level, so Forseti should scan all those resources.

We would like to know where and which custom roles were created for audit/backup purposes.

**Comment by mirons-google** [comment]
**Issue Review**: Mostly code complete and awaiting testing + release @ahoying

**Comment by ahoying** [comment]
Included in 2.0-dev branch, will be part of the 2.0 release, added in #801.
