### ISSUE TITLE
Inventory/Scanner support for Service Account policies

### ISSUE THREAD

**Issue by marcin-kolda** [GoogleCloudPlatform/forseti-security#795]
Please add support for Service Account policies in Inventory/Scanner.

Service accounts are also resources and have their own IAM policies, which can be retrieved using [projects.serviceAccounts.getIamPolicy](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/getIamPolicy) API.

As a potential security risk someone who had e.g. Editor/Owner role, could [act as a service account](https://cloud.google.com/iam/docs/understanding-service-accounts#acting_as_a_service_account) or gain other [service account role](https://cloud.google.com/iam/docs/understanding-roles#service_account_roles), to get control over resources to which service account has access. Currently those IAM are not collected or scanned.

**Comment by mirons-google** [comment]
**Issue Review**: Important use-case. We'll target it in the FS 2.0 release.

**Comment by ahoying** [comment]
This feature is added in #865 and will be included as part of the 2.0 release.
