### ISSUE TITLE
Save the generated deployment manager template to GCS.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#817]
When forseti is initially deployed, it generates a deploy-forseti-timestamp.yaml deployment template in the installer's cloud shell (i.e. installer is the person).

If this deployment template is not saved outside the installer's cloud shell, no one else can use it to redeploy forseti, whether to update it to a new version or make tweaks.  So, it would be nice to save this deployment template to forseti's GCS bucket so that anyone can retrieve this and update to newer version.

**Comment by mirons-google** [comment]
**Issue Review**: Let's do this in Q4.
