### ISSUE TITLE
Documentation for updating new version should also mention forseti_conf.yaml

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#819]
```forseti_conf.yaml``` is a generated file from ```forseti_conf.yaml.in``` during the initial deployment by the setup wizard.  The documentation should mention how to manage this for upgrading to a new version when this file could have changed (e.g. firewall scanner).

**Comment by carise** [comment]
If a release introduces new configuration properties in forseti_conf.yaml, we should also document what properties have changed.

Related: #853

**Comment by blueandgold** [comment]
The conf yaml file is now part of our upgrade instructions.
https://forsetisecurity.org/docs/latest/setup/upgrade.html
