### ISSUE TITLE
Deploying IAM Explain in 1.1.8 fails using the deploy-explain.yaml sample file

### ISSUE THREAD

**Issue by brandon-height** [GoogleCloudPlatform/forseti-security#850]
- Version: 1.1.8
 - IAM Explain
 - Forseti is in its own project

In order to execute: 
```gcloud deployment-manager deployments create iam-explain --config deploy-explain.yaml```

I had to add the following to the  Explain resource properties in deploy-explain.yaml

```network-host-project-id: <sanitized>
    vpc-name: default
    region: us-central1
    subnetwork-name: default
```

Without these it resulted in the following for each property value:

```ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1512065523877-55f37306d8489-80b08b79-2f71712b]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  message: |
    Manifest expansion encountered the following errors: Exception in explain-instance.py
    Traceback (most recent call last):
        return constructor[m](evaluation_context)
# distributed under the License is distributed on an "AS IS" BASIS,
      File "<string>", line 71, in GenerateConfig
    KeyError: 'network-host-project-id'
     Resource: explain-instance.py Resource: config```

**Comment by brandon-height** [comment]
Not sure if its related but even after making those changes and getting a successful deploy there seems to be an issue with the instance that was created (specifically cloudsqlproxy)

cloudsqlproxy seems to be failing with the following error:

```2017/11/30 19:08:11 couldn't connect to "sanitized_project_name:us-central1:forseti-security-20171130095618": ensure that the account has access to "sanitized_project_name:us-central1:forseti-security-20171130095618" (and make sure there's no typo in that name). Error during createEphemeral for sanitized_project_name:us-central1:forseti-security-20171130095618: googleapi: Error 403: The client is not authorized to make this request., notAuthorized```

And as a result forseti on the iam-explain system also fails with 
```Nov 30 19:11:11 iam-explain-explain-vm forseti_api[18298]:   File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 193, in __init__
Nov 30 19:11:11 iam-explain-explain-vm forseti_api[18298]: sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")```

Thanks.

**Comment by carise** [comment]
Thanks for reporting this issue, @brandon-height . We will investigate and get back to you on it.

**Comment by carise** [comment]
Hi @brandon-height, I am going to close this issue as 1.1.9 (and latest master) doesn't have IAM Explain code anymore. I think you've looked at the explain-experimental branch; the Forseti team has a more up to date milestone now [2.0-dev-eap1](https://github.com/GoogleCloudPlatform/forseti-security/tree/2.0-dev-eap1). If you have questions regarding usage of Explain in that branch, please open a new issue. Thanks!
