### ISSUE TITLE
Scanner violation table in 2.0-dev

### ISSUE THREAD

**Issue by jiyunyao** [GoogleCloudPlatform/forseti-security#894]
on 2.0-dev, forseti.services.scanner.

Violation table should not use the same tag as the data model if not managed by data model service. The auditor/scanner is an independent service, it should have a different name.

User should be able to delete violation table

**Comment by blueandgold** [comment]
I will move the model-specific violation tables to a centralized, standalone table, with an extra column for the model name.

**Comment by blueandgold** [comment]
Fixed by PR #1071
