### ISSUE TITLE
Feature Request on forseti model use error handling in 2.0

### ISSUE THREAD

**Issue by jiyunyao** [GoogleCloudPlatform/forseti-security#907]
forseti model use should also examine if the model status.

**Comment by blueandgold** [comment]
This is to handle this kind of error gracefully.

![image](https://user-images.githubusercontent.com/6977544/34278691-4adbbc96-e661-11e7-8a6c-837e4e6b5412.png)

**Comment by jiyunyao** [comment]
Addressed in PR 984
