### ISSUE TITLE
New Features for Explain

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#910]
Features:
* Renaming and regrouping explain, playground functions
* Feasible and necessary playground functions
* Decide on what functions to keep or deprecated in explain and playground.

Explainer:
* denormalize Denormalize a model 
* why_granted Explain why a role or permission is granted for a member on a resource 
* why_denied Explain why a set of roles or permissions is denied for a member on a resource 
* list_permissions List permissions by role(s) 
* access_by_member List access by member and permissions 
* access_by_authz List access by role or permission 
* access_by_resource List access by member and permissions

Playground:
* define_role Defines a new role 
* delete_role Delete a role 
* list_roles List roles by prefix 
* define_resource Defines a new resource 
* delete_resource Delete a resource 
* list_resources List resources by prefix 
* define_member Defines a new member 
* delete_member Delete a member or relationship 
* list_members List members by prefix 
* check_policy Check if a member has access to a resource set_policy Set a new policy on a resource
* get_policy Get a resource's direct policy

**Comment by jiyunyao** [comment]
Regrouping has been done in PR995

**Comment by jiyunyao** [comment]
As we previously discussed, all queries regarding the model go into explainer, all writing actions go into playground. Resource related change abilities are not feasible (The default action when creating or deleting a resource depends on the type of resource. )

Explainer:
- list_roles List roles by prefix
- list_resources List resources by prefix
- list_members List members by prefix
- get_policy Get a resource's direct policy
- denormalize Denormalize a model
- why_granted Explain why a role or permission is granted for a member on a resource
- why_denied Explain why a set of roles or permissions is denied for a member on a resource
- list_permissions List permissions by role(s)
- access_by_member List access by member and permissions
- access_by_authz List access by role or permission
- access_by_resource List access by member and permissions
- check_policy Check if a member has access to a resource set_policy Set a new policy on a resource

Playground:
- define_role Defines a new role
- delete_role Delete a role
Remove - define_resource Defines a new resource
Remove - delete_resource Delete a resource
- define_member Defines a new member
- delete_member Delete a member or relationship
- set_policy Set a policy on a resource
