### ISSUE TITLE
Normalize python method naming convention

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#930]
Forseti branch: 2.0-dev 
We have been using different naming conventions (upper camel case and underscores) in our python codes for method naming and this should be standardized.

Example of methods that used the upper camel case naming convention:
https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/explain/explainer.py
Example of methods that used the underscores naming convention:
https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/dao.py

**Comment by mirons-google** [comment]
Resolved in #963
