### ISSUE TITLE
Store multiple snapshot data within single tables

### ISSUE THREAD

**Issue by marcin-kolda** [GoogleCloudPlatform/forseti-security#955]
Forseti for every run creates new set of tables. Partitioning tables by snapshot time seems to be a bad design.

We wanted to create a dashboard in Data Studio to visualise current violations and their history. We've failed as we're not able to create a single view with violations from last run. It seems that MySQL doesn't support querying dynamic table names in views. It's supported only in Prepared statements and Stored Procedures.

Additionally large number of tables results in UI problems like listing all the tables, etc.

**Comment by blueandgold** [comment]
Forseti 2.0 now stores multiple inventory in a single `gcp_inventory` table.  @marcin-kolda, would be interested to see the type of reports that you generate.
