### ISSUE TITLE
[2.0] Inventory index should contain Cloud SQL instance name to avoid conflicts in exports

### ISSUE THREAD

**Issue by marcin-kolda** [GoogleCloudPlatform/forseti-security#969]
[Inventory index id](https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/inventory/storage.py#L71) in Forseti 2.0 should contain Cloud SQL instance name. This would avoid conflicts in exported data when Cloud SQL instance is recreated.

If every new Cloud SQL instance will start generating IDs from beginning, then we won't be able to join this data between the exports (e.g. if they will be in the same BQ table). This might be also helpful in merging data from multiple Forseti instances, i.e. to get violations from multiple organisations.

**Comment by joecheuk** [comment]
Hi @marcin-kolda , we are planning to add an additional column "root_id" in the inventory index table (or more tables if needed) that stores the root id, an organization id or a folder id depending on how the user install their Forseti application, to make it easier for users with multiple Forseti instances to manage their data. Does that address the concern you have?

**Comment by marcin-kolda** [comment]
Hi @joecheuk,

Our main use case is recreating the whole Cloud SQL instance periodically for the same organisation. In such case root_id won't help. We need a way to distinct Forseti runs (i.e. violations, inventory data) before and after database recreation for the same org.

**Comment by jjawad-google** [comment]
Hi @marcin-kolda this is not currently planned on our product roadmap. An alternative would be for you to add post-processing. If you have any other requirements please let us know and reopen this issue.
